### ISSUE TITLE
Insert a comma, colon, or other user-configurable string when tab-completing nicks

### ISSUE THREAD

**Issue by cmr** [thelounge/lounge#1176]
This would only fire at the start of a line though. Lacking this makes it rather hard for me to get used to lounge.

**Comment by astorije** [comment]
Hi @cmr, welcome on The Lounge!

We have discussed in the past and have decided to keep it that way on purpose. Not adding or adding something after the nick would always offend someone, preferring nothing (I am a strong supporter of the current way) or a different character. Keeping it that way lets people add whatever they want instead to have to backspace.
In the end, it's just a matter of habit, and people get used to it very quickly.

Making this configurable, I'm not hugely in favor of adding an option just for that, but I could be convinced if people really want this. This however requires an overhaul of the settings, so this is not possible at the moment.

**Comment by clandmeter** [comment]
Adding my comment here as I would like to have support for this with some config option.

**Comment by xPaw** [comment]
@astorije, I think we should give in and make a setting for this which would default to empty (e.g. current behaviour). This should be relatively simple to implement, and there's a demand for it.

**Comment by YaManicKill** [comment]
I agree with @xPaw 

Whether this should be in an advanced page, or whether it should just be in the normal settings is something we can bikeshed on this, but I think this should definitely be a feature. Happy to default it to empty, though.

Fwiw, the functionality should only insert the seperator if it is used on the first word in the input, as it is generally accepted behaviour, and people don't want it to do it in the middle of a sentence.

**Comment by astorije** [comment]
As long as it defaults to the current state, I think I am ready to give up. Always amazed by this request though, literally no other messaging system I know let you configure that (Telegram, Slack, Facebook, Hangout, you name it) and yet us lacking it is described as an essential issue 😂 

> Fwiw, the functionality should only insert the seperator if it is used on the first word in the input, as it is generally accepted behaviour, and people don't want it to do it in the middle of a sentence.

So, this is why I was not willing to care about this feature: I have seen all sorts of requests for this. Very quickly, people will ask us 2 fields, one for the first nick-as-word in a message, one for the rest, or to make it obscure like a special format in a single field to support both, or a checkbox "Only for first word", etc. This is very much overkill IMO, especially since it's something you get used to in like 2 days top.

We have so much to do and to maintain already, it pains me that an extra character is such a big deal. But whatever, I won't block this obviously.

**Comment by YaManicKill** [comment]
> literally no other messaging system I know let you configure that

I think the thing is, this is a pretty common IRC feature, but not in any other messaging sphere. And remember that what people like about IRC is the configurability of things. People who use IRC are nerds, and like to change things.

> I have seen all sorts of requests for this. Very quickly, people will ask us 2 fields

Sure, and there may be a point where we have to say no to this, or we can push it off to a plugin when we eventually do that, but I don't think it's a reason to say no to this feature. The fact of the matter is that users care, and so that's something we'll support.

**Comment by astorije** [comment]
Fair points.
Question is then, first word in the message or all of them? What do people prefer / what's common in the IRC client sphere?

**Comment by YaManicKill** [comment]
From the ones I have used, only first word is the most common I've seen.

**Comment by DanielOaks** [comment]
What I've come to expect when tab-completing nicks in IRC clients is:

- If the nick's the first word, append `: ` (colon + single space) after the nick.
- If the nick's somewhere else, append nothing or just a space after the nick.

**Comment by astorije** [comment]
So I'm on board with @YaManicKill's suggestion: setting for first word, nothing otherwise

**Comment by MaxLeiter** [comment]
#85 is slightly relevant

**Comment by stall0ne1337** [comment]
![Here is how IRC Cloud does it. I'm a fan, but should still be configurable.](https://user-images.githubusercontent.com/21053030/27480831-1ae61f52-581a-11e7-91bf-8c8fbf0424dd.gif)

**Comment by YaManicKill** [comment]
@stall0ne1337 Yup, I think that (along with the configuration) is what we are expecting. I might get to this next week after what I'm currently working on, but that all depends on that thing called life.

**Comment by christer88** [comment]
I strongly do not want this to be implemented! It's so annoying to have to remove the space and colon after using nick tab-complete. This also includes nick tab-complete at the start of a sentence. Typing the colon when you need it is way easier.

If this is implemented there must be a way to turn it off.

**Comment by YaManicKill** [comment]
@christer88 We have already agreed that it will be off by default, but there will be a text input for users to choose what they want to do.
