### ISSUE TITLE
How to run lounge in node-webkit on Windows as IRC Client?

### ISSUE THREAD

**Issue by modInfo** [thelounge/lounge#1186]
How to run lounge in node-webkit on Windows as IRC Client.

I packed it to zip after build.
It packs into nw and does not work

git clone https://github.com/thelounge/lounge.git
cd lounge
npm install
NODE_ENV=production npm run build
zip -r ../lounge.zip *
mv lounge.zip to lounge.nw
on windows
copy /b nw.exe+app.nw app.exe

**Comment by astorije** [comment]
Hi @modInfo! This is a question rather than an issue, to which I can only recommend you post it on [Stack Overflow](https://stackoverflow.com/). Since it seems like a question not solely related to The Lounge, you would have more chances to get useful answers there.

Also, we do not have a tag on Stack Overflow, but I'm hoping that we will soon :crossed_fingers:
