### ISSUE TITLE
The input edit marker goes partly behind the keyboard

### ISSUE THREAD

**Issue by avieks** [thelounge/lounge#1200]
![screenshot_20170602-131236](https://cloud.githubusercontent.com/assets/24987062/26723650/d7ca7aea-4795-11e7-99f8-54da80b29990.png)

**Comment by dgw** [comment]
Is the z-level of a system UI element even something the webapp can control?

**Comment by YaManicKill** [comment]
I can't find anything about fixing this and I'm pretty sure we can't control this. But I'll keep it open till we are sure.

**Comment by xPaw** [comment]
Considering this doesn't happen in native apps, I'm assuming it's rendering this way as it thinks it's inside a scrollable container, so scrolling down would reveal more.

**Comment by YaManicKill** [comment]
Yeah, so this happens on every other website I have tried it on. It is a combination of the fact that the marker is included within the browser page itself, and the keyboard is above everything on the browser page, and because the input is right at the bottom of the page.

The only way we could fix this is by adding something below this so the text input isn't right at the bottom. Which we aren't going to do.

Because of this, I'm going to close this.
