### ISSUE TITLE
Decide what to do with package-lock.json

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#1213]
npm5 now automatically creates `package-lock.json` and suggests commiting it to the repository.

Should we commit it or add to gitignore for now?

**Comment by YaManicKill** [comment]
I think we should ignore it just now. It might be useful in the future, but for just now it'll just be noise I think

**Comment by starquake** [comment]
Reading [the purpose](https://docs.npmjs.com/files/package-lock.json) here I think it's useful to add this.

- Describe a single representation of a dependency tree such that teammates, deployments, and continuous integration are guaranteed to install exactly the same dependencies.

- Provide a facility for users to "time-travel" to previous states of node_modules without having to commit the directory itself.

- To facilitate greater visibility of tree changes through readable source control diffs.

- And optimize the installation process by allowing npm to skip repeated metadata resolutions for previously-installed packages.

**Comment by YaManicKill** [comment]
@starquake Yeah, I get the advantages for it.

However, note this bit: `One key detail about package-lock.json is that it cannot be published`. This means that it will only be useful for people using git, it won't ever make it to the published npm package. So there's limited use in that.

We can still use this if people have problems, because npm will still create the file for everyone, so if we find a bug that only happens on 1 particular set of dependency versions, then we can get them to pass us the package-lock.json.

Also, our package.json specifies locked versions anyway, so the only time we would hav ea problem is if a dependency had a specific version that they were relying on that got updated and they didn't have the version locked. 

So yeah, I don't see any reason to add it to the git repo, but it'll still be useful for us in some cases when we can ask specifically for it.

**Comment by astorije** [comment]
Looking at https://stackoverflow.com/a/44323910, it doesn't seem like we'd want this indeed. A shrinkwrap might be a better option, but even then, I'm not 100% sure we need that.
Not a strong opinion either, I'm happy to try out anything.
