### ISSUE TITLE
Switch to ^ semver with dependencies; don't pin versions

### ISSUE THREAD

**Issue by MaxLeiter** [thelounge/lounge#1285]
From ljharb in ##javascript - 

`
22:46 ljharb: pinning versions gives you worse than no security, because it gives you a false sense of security. always use ^ semver ranges. if you want a repeatable build in an app, use a lockfile.
`
`
22:47 ljharb: specifically, pinning a version doesn't pin anything about its subdependencies
`
`
22:47
ljharb: so pinning a version doesn't give you a guarantee that nothing changes - all it does is ensure you won't automatically receive bugfixes and security patches.
`

**Comment by YaManicKill** [comment]
No.

Sure, it doesn't pin subdependencies, that's fine. But it gives a certain level of reliability. We have had issues with builds failing because of silent updates, and although that can still happen, it hasn't happened since we pinned dependencies. It happened to me on several products and hasn't happened to me at all since I started pinning.

And we do get patches, because we use greenkeeper.

This way, updates are visible rather than invisible. If you have the carat, how do you know when to rerun npm install? Whereas with greenkeeper, we always know when to do it, because there has been a change.

**Comment by astorije** [comment]
I'm 👎 as well. @xPaw, what do you think?
