### ISSUE TITLE
Keep track of nick auto completion order on the server

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#1313]
We currently sort it on the client when messages are received, which means the order is lost on page (re)loads.

We will need this to reduce traffic (e.g. #1194), and consistent sorting across devices and page loads.

This probably can be implemented by adding `lastMessage` timestamp on user object in channel, and updating it when a message is received on the server. Later this timestamp can be used to fix the order on the client.

**Comment by astorije** [comment]
As a feature, I'm already not a fan of this ordering. It's nice to have the last 2-3 "talking nicks" available when hitting <kbd>Tab</kbd>, but it's frankly niche that we have to keep a precise order of everything. I do believe that the new autocomplete dropup helps a lot answering the underlying usability concern, and IMO #1086 will make this even nicer.

That being said, since people do apparently like this feature: as for keeping this on the server, I'd really _really_ avoid doing that. It's a lot of effort and superfluous code for a tiny extension to this feature. There are a ton of edge cases and I really don't want to go there.
Instead, what I think we should be doing is that, on the client, when loading a channel (like when page is reloaded), use the messages to be rendered to order the nick autocompletion values. Yes, this will not be 100% precise like keeping track of them on the server since the beginning of time, but it doesn't have to be. Using the last 100 messages (minus number of joins/parts/etc.) would give enough precision to be indistinguishable for humans 😅.

**Comment by xPaw** [comment]
> That being said, since people do apparently like this feature: as for keeping this on the server, I'd really really avoid doing that. It's a lot of effort and superfluous code for a tiny extension to this feature. 

This should be accomplished in about 2 lines of code on the server (1 variable definition on user object, and 1 to update it in message event).

**Comment by astorije** [comment]
Okay so maybe I misunderstood your original issue: with `lastMessage`, are you trying to only store the most recent message/nick? So if nicks are a, b, c, d, and b is saying something, order will be "b, a, c, d"; after that, if d says something, b gets "forgotten" and order is "d, a, b, c"?

**Comment by xPaw** [comment]
It would store when each user sent their last message.

**Comment by xPaw** [comment]
Just realized this is a dupe of #289
