### ISSUE TITLE
Custom CSS plugin

### ISSUE THREAD

**Issue by YaManicKill** [thelounge/lounge#1447]
As we have the wiki page for some custom css, maybe we should support "partial themes" or "custom css plugins" that you can have multiple of, so we can share these tweaks in an easier way.

I imagine it would work exactly like the #1266 does, but it'll include all of the ones you have, you don't select one of them.

Maybe we should have a way to select them in the client, but I'll think about that later.

**Comment by xPaw** [comment]
I imagine this plays nicely with the plugins in general. If specified as a plugin (not theme), let it have an array of css files that lounge should additionally load.

**Comment by YaManicKill** [comment]
Yeah, good plan. It's not a "theme" as such, so a "plugin" would make more sense rather than creating a whole new category.

**Comment by astorije** [comment]
That's a pretty cool idea!
It turns out, you can already do a lot with CSS only, so yeah, that'd be great. I remember seeing a couple of CSS-only packages for Atom and thought it was a pretty good idea at the time 😅 

One thing though (I believe that's what @xPaw meant but I'm not 100% sure), instead of make them a special type of plugins (or themes), I'd call it a Custom CSS API or whatnot, and plugins can use it to register CSS snippets or files.
That way, you can have a package that's custom CSS-only, or that uses this feature as part of something bigger, etc.

In general, I like the idea of having a bunch of APIs that we can name. That way, it's easier to relate to, talk about, reference in documentation, examples, etc. Each API would be a capability to integrate with The Lounge, and as new use cases / capabilities arise, we'd have new APIs: authentication API, custom CSS API, command API, etc.
I haven't studied Atom package system much, but I see them coming up with new APIs for different part of the product, so I wouldn't be surprised if that's more or less how they operate.

**Comment by YaManicKill** [comment]
> instead of make them a special type of plugins (or themes), I'd call it a Custom CSS API or whatnot

This is what I understood from what @xPaw suggested, and I agree. Plugins are plugins.

**Comment by xPaw** [comment]
We can basically just have `lounge.stylesheets` array in `package.json` and just loop through it for every loaded plugin and add `link` in `index.html to load each one of them.

**Comment by YaManicKill** [comment]
We can basically just have `lounge.stylesheets` array in `package.json`

Well, let's not define where they have to put them. The file doesn't matter, as long as it is coming in the default file that we require. Because plugins that want to do a css tweak as well as something Javascripty will need to provide us a JS file rather than the package.json, and realistically we don't care.

We'll import the plugin, and check for a number of things. That will be one of them.

**Comment by xPaw** [comment]
@YaManicKill Pretty much, mostly the same logic that we use for themes.

**Comment by xPaw** [comment]
Related: #456

**Comment by astorije** [comment]
One element of the Custom CSS API I'd see would be a registration method. Something like `lounge.registerCssFile("my-file.css")` and that would be the lowest level to add some custom CSS.
That way, one can register files dynamically, based on config or whatever.
Then if we have other mechanisms, such as loading from `package.json` or wherever, our loader would under the hood use that same mechanism.
