### ISSUE TITLE
Truncate channel when switching to another channel

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#1461]
Now that we don't run a 10 second timer to trim messages, idle channels do not get trimmed if you load a lot of history and then switch to another channel.

**Comment by astorije** [comment]
So, one thing that I find really annoying on The Lounge is that when you switch channels, you lose your scroll. It's a shame because I believe it's not like this by default, it's something we force, no?
I'd like that when you switch channels, if you were not stickied at bottom, your scroll will be preserved.

Then the issue is what if I was not at bottom, switched, never came back. I'd say history of non-stickied idle channel should be trimmed but less often, like with a 1000 buffer (instead of 100) or something.
Better but more complicated would be that a post-`IntersectionObserver` world would load in both directions, so that if you're not at bottom, you scroll down and more messages get loaded. That would be sweet.
