### ISSUE TITLE
Resetting a user's password requires The Lounge to be restarted before they can login.

### ISSUE THREAD

**Issue by MatthewDwyer** [thelounge/lounge#1559]
Maybe I am doing something wrong, but if I use lounge reset joe to change joe's password, he can't use the new password until I restart The Lounge.  Shout has the same issue.

**Comment by astorije** [comment]
This is a known issue unfortunately, see https://github.com/thelounge/lounge/issues/598 and https://github.com/thelounge/lounge/pull/779#issuecomment-265508333.

Reason is because currently we only "watch" creations and deletions of user configuration files. When a password is modified, nothing happens.

It is probably not a difficult thing to do if you want to try helping with a contribution, but we just haven't got to it so far.
