### ISSUE TITLE
Can I Add Custom Emoticon?

### ISSUE THREAD

**Issue by dateno1** [thelounge/lounge#1603]
Can I add custom Emoticon set and menu for show list on My Server?

It common function on messenger
http://i64.tinypic.com/ok0976.png
like this

If i was paste image address manually work well but very inconvenient
http://i68.tinypic.com/2whp0lw.png
like this

**Comment by astorije** [comment]
As far as I know, all apps or systems that offer custom emoji are doing it in a proprietary manner. 
Said otherwise, because we are hooking into IRC protocols, which I believe doesn't support custom emoji, there is nothing we can do. Even if we were to send something custom, other parties (i.e. any other user on the channel) wouldn't display it.

Closing it as impossible, @xPaw feel free to re-open if I'm missing something.
