### ISSUE TITLE
LDAP Auth succeeds with blank password

### ISSUE THREAD

**Issue by keegan** [thelounge/lounge#1724]
When a user inputs no password, but gives a valid username in LDAP, they can authenticate successfully.

This should be a very simple fix, this block:
```
if (!user) {
    return callback(false);
}
```
can simply be replaced by this:
```
if (!user || !password) {
    return callback(false);
}
```
in the beginning of the different LDAP auth methods

**Comment by astorije** [comment]
@eliemichel, @thisisdarshan, @gramakri, @lindskogen, you've all been very helpful in the past regarding our LDAP support, could you advise on this? :)

**Comment by gramakri** [comment]
I checked quickly in the Cloudron.io app and LDAP auth does not succeed with an empty password. You can try this on the demo at https://my-demo.cloudron.me (username: cloudron password: cloudron).

Quickly reading the code, it just passes on the password to the bind logic at https://github.com/thelounge/lounge/blob/master/src/plugins/auth/ldap.js#L19 . @keegan can you explain the code flow here on your LDAP server?

**Comment by astorije** [comment]
> I checked quickly in the Cloudron.io app and LDAP auth does not succeed with an empty password.

@gramakri, there was a recent refactor of the LDAP support at https://github.com/thelounge/lounge/pull/1478. Is the Cloudron.io app running the previous version, or the current one?
Reason why I'm asking is because it might have been working before the refactor, then a bug could have been introduced in the refactor.

**Comment by ollipa** [comment]
I can reproduce this on my instance which is running 2.6.0. Authentication fails when using an incorrect password but is successful if password field is left blank. Hopefully this gets fixed fast...

**Comment by dgw** [comment]
Relevant? https://security.stackexchange.com/a/6714/601

Excerpt:

> For LDAP, however, the common case is that the server allows logins with **any username and an empty password**. The user will end up as being anonymous. But the login returns a status code indicating success.
> 
> […]
> 
> So, now imagine that the login is not done by the user directly. But the user logs into some other software, and this software takes the username and password and does an LDAP login behind the scenes.
> 
> If this software blindly trust the "success" result from the LDAP server **without having a special case handling for empty passwords, boom**. (emphasis in original)

As a side note, a Google search for "ldap password empty" turned up a fair number of tickets and discussions about similar issues in various software products and frameworks.

The long and the short of it is, common LDAP server implementations allow the `unauthenticated` bind mode (non-null username, null password) by default, which naïve LDAP consumers interpret as a successful `authenticated` bind instead. So, it's possible to fix without changing The Lounge's code by reconfiguring the LDAP server to reject null passwords (disabling the `unauthenticated` bind mode)—but since allowing null passwords is a default setting in many LDAP implementations, #1725 should be released as soon as possible (hopefully faster than #1650 because this is a security issue :stuck_out_tongue:). Do I smell a 2.6.1 release?

**Comment by gramakri** [comment]
@astorije Yes, Cloudron is using lounge 2.6.0.

@dgw Oh, good find! Cloudron has it's own LDAP server and indeed it doesn't allow such binds. I guess this is some (mis)feature of LDAP servers. I have no way to test but trust the source you have quoted.

**Comment by astorije** [comment]
> As a side note, a Google search for "ldap password empty" turned up a fair number of tickets and discussions about similar issues in various software products and frameworks.

:man_facepalming: :woman_facepalming:
