### ISSUE TITLE
Try to get rid of dtrace-provider dependency used by ldapjs

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#1756]
`ldapjs` is using 2 versions of `dtrace-provider`, there are multiple issues and PRs on https://github.com/mcavage/node-ldapjs trying to fix/remove it, but the author is inactive. Perhaps there is a better fork/alternative to `ldapjs`?

**Comment by KarlPerkins** [comment]
The version of ldapjs included in lounge has dtrace-provider referenced as both an optional and a regular dependency while the current version of ldapjs only lists it as an optional dependency.  I removed the reference of dtrace-provider from the regular dependency list and from node_modules, and was able to test and build with out issue.

**Comment by jcrben** [comment]
http://forked.yannick.io/joyent/node-ldapjs - not much
might be best to just fork ldapjs and maintain our own version, if possible

personally found this because I'm working thru 
![image](https://user-images.githubusercontent.com/5614134/34596700-c7de2522-f196-11e7-9579-fa621caf2990.png)

**Comment by astorije** [comment]
Hey @jcrben, thanks for your input!

Personally, I would prefer not to have to fork and maintain our own version of this 😩 
We are already understaffed and overwhelmed, and The Lounge is really not about LDAP, so if we can keep this outside of our plate, that's one less thing we have to spend time on.

But yeah, removing `dtrace-provider` would be so great...

**Comment by jcrben** [comment]
how intertwined is ldapjs then? maybe it could be removed entirely

in any case, if ldapjs is unmaintained, then it's an illusion to think that it's not on The Lounge to maintain it on some level - e.g., if there's a security issue, it's on us - importing a library means ownership

...as far as dtrace, then I ended up with 
![image](https://user-images.githubusercontent.com/5614134/34596877-096fbeb4-f198-11e7-9d4b-d6b251dbd5c6.png)
looks like I'll have to dig thru one of these possible causes https://github.com/trentm/node-bunyan/issues/525#issuecomment-319836630

ultimately I'm using https://github.com/thelounge/docker-lounge and not trying to run this locally anyway so it shouldn't be that big of a deal, but was just messing with the local build for a second

**Comment by astorije** [comment]
> how intertwined is ldapjs then? maybe it could be removed entirely

It is necessary for our LDAP support/integration.

> in any case, if ldapjs is unmaintained, then it's an illusion to think that it's not on The Lounge to maintain it on some level - e.g., if there's a security issue, it's on us - importing a library means ownership. it could just be one commit to strip out dtrace, submit a PR upstream to be a good citizen, and stay frozen (aside from security) thereafter

Well, things are not that black and white :)

I do indeed believe that it's not on The Lounge to maintain it, and I therefore refuse to personally take ownership of it, and I think I can speak for other @thelounge/maintainers when I say our TheLounged lives are already full enough to take another responsibility.

Additionally, no one in the core team actually uses LDAP, or our LDAP integration, so it makes maintaining more difficult, and not as "spontaneous", if that makes sense. However, there is a very strong need for LDAP in the community, and we've had a few good contributions in that sense.
What that means is that we have always expressed that our LDAP integration is not exempt of bugs, and if you use it, you're a bit on our own.

Thanks for bringing this up though, because it is not clear enough, so in my [work on revamping the docs](https://github.com/thelounge/thelounge.github.io/tree/astorije/better-docs), I will make sure to clearly document that the LDAP integration is at the user's risk.

Now in terms of support, we have made a few [calls for help](https://github.com/thelounge/lounge/pull/1725#issuecomment-347051109), but it is harder to find maintainers than contributors! :)
So until we have people actively helping us with our LDAP integration, I don't believe there will be the ownership you mentioned, which is the ideal case I agree.

Oh, re: opening a PR, I totally agree that it would be great, and again, if someone wants to help with that, they are more than welcome. It is unlikely it will bear fruit however, because there is already an upstream PR to solve this issue on `node-ldapjs` that is not getting any activity.

> ...which brings to mind that a recommendation to use the docker container could save some frustration

New docs (planned for v3) have their own [Docker section](https://github.com/thelounge/thelounge.github.io/blob/astorije/better-docs/_docs/install-and-upgrade.md#docker), mentioned next to our packages (Debian/Ubuntu and Arch), npm releases, and running from source.

**Comment by MaxLeiter** [comment]
Also with regards to that last point: #491
