### ISSUE TITLE
how to host this online in hosting space

### ISSUE THREAD

**Issue by syam3526** [thelounge/lounge#1766]

**Comment by xPaw** [comment]
https://thelounge.github.io/docs/getting_started/install.html

You will need SSH access.

**Comment by syam3526** [comment]
can u give the procedure,

**Comment by astorije** [comment]
Hi @syam3526!

For this type of questions, your best bet is to identify which hosting solution you prefer (there are a lot, so you will need to do your own research and weigh in your requirements: budget, capabilities, etc.) then if you are stuck, [ask your question on Stack Overflow](https://stackoverflow.com/questions/ask?tags=thelounge) with the tag `thelounge` so that other people can easily find it.

Good luck!

**Comment by syam3526** [comment]
thankss
