### ISSUE TITLE
Make it possible to hide the address bar in Chrome for Android

### ISSUE THREAD

**Issue by dgw** [thelounge/lounge#189]
Was hesitant to use the generic "on mobile" in the issue title, because I don't know what other browsers/platforms have this issue, so decided to specify what I'm using. It can always be expanded later.

On most pages, Chrome for Android hides the address bar when the user scrolls down the page (drags a finger up). It naturally moves out of view with the scrolling content.

The Lounge doesn't do that, because when the user scrolls, it's *only* a pane within the page that is being scrolled. So, the address bar sticks around, taking up 2-3 chat lines' worth of vertical space. Granted, on my 6" phone this isn't a huge deal, but on smaller screens it consumes a greater percentage of the available content area.

Frankly I don't even know where to start with this, but surely there is a way to allow Chrome (and other mobile browsers that use similar behavior) to hide the address bar once The Lounge has loaded completely. There are some tricks around, e.g. [at HTML5 Rocks](http://www.html5rocks.com/en/mobile/fullscreen/), but are they too "quirk-y" for use here?

**Comment by YaManicKill** [comment]
One thing to note: add it to your home screen. Then when you launch it it
is in full screen.

**Comment by astorije** [comment]
What @YaManicKill says. This will solve your issue, @dgw :-)

**Comment by dgw** [comment]
Sure, it "solves" this issue by changing how I have to launch The Lounge, moving The Lounge from a browser tab to a separate app in the task switcher, and requires me to keep an extra icon on my home screen.

Don't you find that kludgey, from the user's perspective? I do. Better to make the app behave as nicely as possible under all conditions, including when it isn't afforded the privilege of a dedicated icon in the user's launcher.

**Comment by YaManicKill** [comment]
FWIW, I wasn't saying it was a "fix", but I did want to bring it up as a solution for you in the meantime. Honestly, I doubt anyone will pick this up anytime soon. I'm not a huge fan of any of the hacks suggested in the html5 rocks site (the only one that would work and I could deal with would be the one about auto-scrolling slightly down, but even that still doesn't feel nice).

So don't take my comment as "I don't care, the solution is putting it on your homescreen" more as "hey, here's a way you can get what you want while there isn't a good solution". Because I don't think any of those are good solutions (fullscreen mode is different from just hiding the address bar, which I don't think is something we want to run The Lounge in).

**Comment by dgw** [comment]
Today's lesson: Tone is hard in text-only communication. Sorry for misinterpreting what you said, @YaManicKill.

As I said, it's not a huge deal for me right now because my screen is so large. But you are right—even the least offensive of the hacks I was able to find don't feel nice, and the hackier they get the less I'd like to know about them being used.

I do hope someone who knows more about this particular quirk comes along. It seems like it would be a tricky implementation to even allow scrolling the whole Lounge page, which also seems like the simplest idea.

Mobile is still a frontier, I see. :wink:

**Comment by maxpoulin64** [comment]
I'm not sure how possible that is, especially in terms of reliability. The scrollTo hack works, but if you look at the demo, they used it on a button press. While I've seen some sites do it on load, there's one huge flaw that is, if for any reason the user makes the address bar show again then it will be stuck there. This is really unfortunately a side effect of being a browser app. Browsers have an address bar.

Adding the webapp to the home screen is unfortunately really the way the whole thing has been designed.

**Comment by astorije** [comment]
In terms of user perspective, I find the current state of things pretty clear: if it's a web page in the browser, it feels like a browser. If it's a web app that behaves like a native app, it feels like the browser is not involved.
It is actually more kludgey to have things in-between, such as a web page (tab) that appears in the browser but looks and behaves like an app.
The only thing that can be made better here is #35, so that when browsing the client, the user gets prompted this can be added as a packaged application. But different story :-)

Anyway, I think we all agree relying on ugly hacks for this kind of things is not ideal. Let's wait for mobile ecosystem to evolve. The external app feeling when pinning a webpage on the home screen is actually about 2 years old only, so things can definitely evolve, and the closer we stay from the browser, the more likely we'll be compatible.

**Comment by maxpoulin64** [comment]
So what position are we taking on this? Since there is no reliable and clean solution, I think we should close this as a wontfix.

**Comment by astorije** [comment]
Agreed with @maxpoulin64.
I actually don't think there is anything to fix on our end, as @YaManicKill explained earlier.
