### ISSUE TITLE
Document which node versions are supported.

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#231]
![703-imported-1453533598-schedule](https://cloud.githubusercontent.com/assets/613331/14225177/debb204e-f8c1-11e5-8bad-cbc4dd60f806.png)

Looking at the picture, node 0.12 is no longer an active LTS as of this month. We already removed 0.10 from Travis due to failing linters. Looks like there are problems running 0.10 on `irc-framework` branch too.

We can also use `engines` field in `package.json` to make it more clear for users: https://docs.npmjs.com/files/package.json#engines

**Comment by YaManicKill** [comment]
I would say we keep 0.12 support, unless there is a good reason not to, until the end of the maintenance period. 

Node 4 has only been out for a year, and there are plenty of people that are still on 0.12. I'm fine with the fact that we've already dropped 0.10 because there were reasons to do that, but until we have a good reason to drop 0.12, we should keep support for it until the end of the year.

**Comment by xPaw** [comment]
cc @thelounge/maintainers.

Looks like there are random issues popping up when running master on node 0.10. Can we add `engines` for the next release?

**Comment by maxpoulin64** [comment]
@xPaw seems fine to me. I don't see any reason to support old version of node, it's not like we're a big library or anything where that would break other people's code. I doubt we'll ever need to run on some kind of production machine that requires an obsolete version of node. If the user wants to run Lounge on such a machine, they can just compile the latest node release and run Lounge on that.

**Comment by xPaw** [comment]
That is a good point, as we are providing an "end product". The question of which version should be the oldest supported still remains though. I'd make it 4.0.0.

**Comment by YaManicKill** [comment]
I'm still going to argue for 0.12 until we have a reason not to. It is in maintenance till the end of the year, so it's still legitimate to be on it, and we aren't doing anything that shouldn't work. If we come across something that doesn't work, or we have a few weird bugs that we don't want to spend time on, then sure. But I think we should support 0.12 until at least end of maintenance. After that, there's no legitimate reason to be on 0.12.

But perfectly happy with adding the engines asap.

**Comment by xPaw** [comment]
4.0 was released after merging iojs back into it, and it includes a lot of the improvements and a major V8 engine bump. Who knows how many discrepancies there can be without us being aware of them.

https://github.com/nodejs/node/wiki/API-changes-between-v0.10-and-v4 (applies to 0.12 too)
Just reading that list I saw that `fs.existsSync` is deprecated, and we still use it.

**Comment by YaManicKill** [comment]
> Who knows how many discrepancies there can be without us being aware of them.

That's not a reason. There will be a major V8 bump in 6.0.0, but that doesn't mean we'll drop support for 4 and 5.

**Comment by YaManicKill** [comment]
As mentioned in the IRC, @xPaw was meaning the new ES6 features that V8 has brought us since 4.0.

With that in mind, I am happy for us to support 0.12 until someone wants to use one of the ES6 syntax features included in 4.0, and then we drop 0.12, due to the fact that 0.12 leaves LTS in 5 days.

If there is enough call for a 0.12 compatible version, then it wouldn't be hard to create a fork that uses babel to allow that to happen (literally, it would be like 10 minutes work to set up if you've used babel before).

**Comment by astorije** [comment]
👍 on pretty much everything that was said and concluded to. A few comments on #280 details but overall OK with the idea.
