### ISSUE TITLE
Fast-forward commits

### ISSUE THREAD

**Issue by YaManicKill** [thelounge/lounge#235]
So, looks like github has added fast-forwarding as an option when merging.

Shall we move to that rather than merge commits? Always looks nicer.

![screenshot from 2016-04-02 16-31-51](https://cloud.githubusercontent.com/assets/2162657/14227225/90067c12-f8f0-11e5-979e-dc9fb6b1032d.png)

**Comment by xPaw** [comment]
Squashing some PRs is not desirable.

**Comment by YaManicKill** [comment]
I would argue that if you need multiple commits, it's probably too big for 1 PR. But I like the idea of fast-forwarding, and it's annoying they don't have an option for fast-forwarding without squashing, but I think that's better than having merge commits. And it would stop having problems where someone has multiple commits because we can just squash them this way.

**Comment by xPaw** [comment]
Well, look at #167 :)

**Comment by YaManicKill** [comment]
Alright, I guess so. I sincerely hope you will cut down the number of commits on that one at some point though. 40 seems...unnecessary.

However, I would say that I think that most things we could use the fast-forward and squash method and for the occaisional one that needs multiple commits (these should be quite rare) then we can do a merge commit.

**Comment by lindskogen** [comment]
Since you seem to prefer people to squash PR:s, maybe you should enable the option?

**Comment by MaxLeiter** [comment]
I think this can be closed? Current way of merging is fine

**Comment by astorije** [comment]
> Current way of merging is fine

Agreed. Also, note that I am using the list of merge commits to build the change log each time. I know this is rather specific and there are probably other ways to do so, so it's more a tie-breaker than a definitive argument, but it has shown as the easiest and best way to do so for me.

> And it would stop having problems where someone has multiple commits because we can just squash them this way.

About that, GitHub also offers to let maintainers modify a branch by default when a contributor opens a PR. That could be a way for us to easily squash without requiring contribs to do so and wait for another back-and-forth.
Actually, this is a good candidate as a sibling for `./scripts/run_pr.sh` :-)

> I think this can be closed?

Done, thanks for triaging.

**Comment by YaManicKill** [comment]
Reopening time!

Since I opened this originally, they added a new "rebase and fast forward" option, which removes @xPaw's issue, so that we don't have to squash.

I really would prefer if we rebased and merged rather than squashing. If you've ever looked at the list of commits on github to see the changes, it is quite awkward when it's a really old commit and a merge commit, as the merge commit is the only one you see, so it's hard to see the author. On top of that, we end up having twice as many commits as we need to.

It just looks much nicer not having merge commits.

If people **still** are against fast-fowarding, then fine. But I thought I'd try now that we at least have an address to @xPaw's comments.

**Comment by astorije** [comment]
@YaManicKill, while the squashing issue is resolved, I still rely on merge commits at release time to build the changelog entries. I have tried different ways (from the PR list, the milestone, etc.) and every time I come back to the commit history on master as it's the easiest, fastest and most accurate way for me to do so. It already takes quite some time to draft a release carefully, I cannot decline something that helps me doing it 😅 

On another note, I know some of my coworkers tried to use the Rebase and Merge option to merge PRs at work, and ended up not doing it anymore because (I'm not sure of the details to take the rest of this sentence with a grain of salt) GitHub didn't keep track of the links between all those correctly, or something.

So I still think we don't need to worry about that, current way of merging is fine, especially since blaming/looking through history from the file itself actually keeps authorship as it should.

**Comment by YaManicKill** [comment]
I disagree, but I guess I'm outnumbered on this one. Closing. I won't bring it up again.
