### ISSUE TITLE
Use path.join everywhere

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#301]
I've noticed in some places the folders are joined like `HOME + "/users"`. Using `path.join` is better.

**Comment by astorije** [comment]
Why is it better? If it's just a concatenation between two strings (like in your example), then `+` is just fine.

**Comment by maxpoulin64** [comment]
@astorije: The latter is cross-platform and independent of whatever path separator an OS uses. So for  example on Windows you'll get a path like `.lounge\users\astorije.json` instead of `.lounge/users/astorije.json`. In the case of Windows it works, but it's just considered better/good practice to use the helper.

**Comment by astorije** [comment]
Aaaaah, that'll teach me to read things too quickly!
I read `join` as in `[HOME, "users"].join("/")` and really I didn't see the point... 👊 

Then yes, I fully agree!

For the record, [here is the `path.join` doc](https://nodejs.org/api/path.html#path_path_join_path1_path2).
