### ISSUE TITLE
Add /AMSG and /AME (Message all open channels)

### ISSUE THREAD

**Issue by torriz** [thelounge/lounge#311]
There doesn't seem to be a [/AMSG](http://script.quakenet.org/wiki/Amsg) client function/command atm.

I asked on #thelounge channel, and the response I got was that it shouldn't be too much code to make it work..

**Use case:** Easier PCW/Scrim finding for teams in various games..

**Comment by xPaw** [comment]
Two questions:
- Should it send to all channels client is on, regardless of the network? Or should it send it to all channels user is in on current network?
- Should we be sending separate PRIVMSG for each channel, or combine all channels in a comma separate list?

**Comment by dgw** [comment]
Two opinions:
* `/amsg`/`/ame` should broadcast to **all channels user is in on current network**. I have yet to come across a client that messages literally all open channels regardless of network. (Textual, for one, supports scoping `/amsg` to all networks, but that preference defaults to false.)
* IRC servers tend to rate-limit/flood-detect based on lines sent, so **combining all channels into a comma-separated list** seems the most prudent choice.

**Comment by maxpoulin64** [comment]
I think this is a pretty niche feature that would have a better place in a plugin. It's nice to have a lot of features in the client but we have to be careful of what we include and support by default. It would be bad if we started getting a bad reputation with IRC operators because we include everything by default and our client ends up being the annoying client with way too many scripts on it. Mainly, @vectr0n pointed out as an IRC admin that it's one of the features he has to fight a lot due to spam. While of course we can't prevent users from doing it (and don't want to!), I think our client needs to stay as clean as possible with sensible defaults so bouncer admins don't have to go through the config and disable everything but instead enable the things that they do want.

It's definitely a nice little quick feature I'll do as one of the first demo/example plugins tho!
