### ISSUE TITLE
Starting with " /" (whitespace + slash) does not send the message

### ISSUE THREAD

**Issue by astorije** [thelounge/lounge#319]
This was fixed in a previous PR (~~https://github.com/thelounge/lounge/pull/154 I believe~~ Actually, I'm not sure we ever fixed this...) to allow escaping commands with a slash (`// something...`) or a leading whitespace (` /something...`).

**Comment by maxpoulin64** [comment]
We do have escaping with `//something`. Apparently messages starting with a space [are expected to be dropped](https://github.com/thelounge/lounge/blob/master/src/plugins/inputs/msg.js#L4), oddly enough. Probably a shitty check where one should just check the length of the array.

**Comment by astorije** [comment]
Actually, typing ` /something` is treated as sending the `something` command, not totally dropped... I get an `Unknown command` in the lobby.

I believe the culprit is rather [here](https://github.com/thelounge/lounge/blob/605036fb1ee5ac896fd3ef970eb4bcc5f746377e/src/client.js#L268-L302) and not in the snippet you posted.

**Comment by MaxLeiter** [comment]
I think more specifically the issue is here: https://github.com/thelounge/lounge/blob/605036fb1ee5ac896fd3ef970eb4bcc5f746377e/src/client.js#L274

'text.charAt(1) === "/"'

**Comment by maxpoulin64** [comment]
@MaxLeiter: that's impossible. The message starts with a space, `text.charAt(0) !== "/"` will be true and the second one isn't even checked.

We do however end up with this:

```
> "say  /test blah".split(" ");
[ 'say', '', '/test', 'blah' ]
```

which means it will get dispatched to the handler for `say`.

Except this is not the case, because turns out [derp, this is the problem](https://github.com/thelounge/lounge/blob/605036fb1ee5ac896fd3ef970eb4bcc5f746377e/src/client.js#L270).


```
var text = data.text.trim();
```

Oops.
