### ISSUE TITLE
[proposal] Change mobile side menu to overlay

### ISSUE THREAD

**Issue by dgw** [thelounge/lounge#398]
Currently, when the side menu slides out on mobile, it pushes the chat over. I had the thought that it might look better if the menu simply slid out on top of the rest of the page, like an overlay. @maxpoulin64 says that would be easier to implement, too, so might help with #393.

**Comment by maxpoulin64** [comment]
Actually, thinking about it, that's a problem for non-touch devices, because the overlay menu would open on top of the menu icon, so it would be impossible to close on desktop. We could put the button on top of everything, but the current default theme makes it difficult to do that in a way that makes sense. We'd need to materialize the whole default theme to do that, so we can have a fixed menu-bar and get rid of those borders around the real content. Right now even if we make the menu bar persistant, it's going to look weird due to all the borders.

**Comment by dgw** [comment]
Right now, using a window narrow enough to trigger hiding the sidebar, it's annoying to use with a mouse because the menu button changes position on click. So maybe a fixed top bar would be a good idea…but it would take some redesign work. This is probably a longer-term thing than I had anticipated, but good to bring up nonetheless.

**Comment by YaManicKill** [comment]
The other option is another button in the sidebar that collapses it.

**Comment by YaManicKill** [comment]
We have the slideout menu for mobile now. Would this add anything to it? Not sure it would look any better, and it would cause some awkwardness with the buttons, etc. 

I guess the question is... is it better to hide the beginning of all the messages, or the end of all the messages? I reckon we keep it as it is. If someone thinks differently, feel free to reopen.
