### ISSUE TITLE
Provide prebuilt distro packages

### ISSUE THREAD

**Issue by maxpoulin64** [thelounge/lounge#414]
I'm creating this issue following a discussion with @astorije and the handling of daemon management. The problem we'd want to solve is that for the end user, it's not very clear how to install The Lounge, how to run it, etc. Right now everyone has their way, and many of them are wrong and/or incomplete and/or impractical. Adding support for automatically daemonizing would fix one of the problem as the client would just fork in the background, but that still doesn't deal with starting back up on boot or on crash. Other projects don't really ship those either, they just have the luxury of being supported by the distro maintainers and being part of the main repos. Many tools and utilities people are used to are, in fact, provided by the distro. Everything one can manage with `service XXXX restart` or `/etc/init.d/XXXX restart` is in fact provided by the packagers for that particular distro.

Thus, I suggest we create a bunch of extra repos, one for each package format we want to deal with, and manage those. I can take care of that and automate the builds on my server, and also take input from the community to improve those packages. Those would be:
- `arch-lounge` (for Arch, Antergos and Manjaro) ([which I already maintain here](https://aur.archlinux.org/cgit/aur.git/tree/?h=thelounge) but would move to the org)
- `deb-lounge` (for Ubuntu, Mint and Debian)
- `rpm-lounge` (for CentOS, Fedora and others)

(I would personally do `lounge-xxx` as I think it makes more sense, but we have `docker-lounge` already so ¯\_(ツ)_/¯)

This way, our users could just download the `.deb` on their Ubuntu boxes, run `service thelounge start` and be done. Configure in `/etc/thelounge/config.js`. Everything would run smoothly exactly like nginx, mysql or other daemons work.

Thoughts?

**Comment by astorije** [comment]
> Thoughts?

I highly 👍 that!
The way I see it, this opens the door to the following on Ubuntu/Debian: `apt-get install thelounge && service thelounge start`. That would be great, and streamline the whole process.

> I can take care of that and automate the builds on my server

Pretty sure we can leverage [Travis CI deployment feature](https://docs.travis-ci.com/user/deployment) to help with this. But bring the repos here is a first necessary step, and automation can come and get improved over time.
(Speaking of which, should I update the Travis CI configuration so that it would [upload the built project to the GitHub releases](https://docs.travis-ci.com/user/deployment/releases)? Right now releases only contain the source, without the built assets, how useful would that be to have them there? I believe @xPaw wanted that)

> * `arch-lounge` (for Arch, Antergos and Manjaro) ([which I already maintain here](https://aur.archlinux.org/cgit/aur.git/tree/?h=thelounge) but would move to the org)

I'd say let's start with this one as it already exists and is maintained. We can have this one up and running very soon, and if others want to step in to help with other distributions, then they have a pattern to re-apply.

> (I would personally do lounge-xxx as I think it makes more sense, but we have docker-lounge already so ¯\_(ツ)_/¯)

No big deal, really. I remember having that discussion with @williamboman when creating [`docker-lounge`](https://github.com/thelounge/docker-lounge), and with myself when creating [`ansible-lounge`](https://github.com/astorije/astorije-lounge) (which could really use such daemon instead of supervisor btw :P). I don't remember what were the arguments, but let's say they really made sense at the time :D

**Comment by astorije** [comment]
> * `deb-lounge` (for Ubuntu, Mint and Debian)

By the way I know how busy @JocelynDelalande is, but if he wants to take care of one and only one thing, this would be a really good one... 😄

**Comment by YaManicKill** [comment]
[I'll just leave this here](https://insights.ubuntu.com/2016/06/14/universal-snap-packages-launch-on-multiple-linux-distros/)

**Comment by YaManicKill** [comment]
So, we now have arch and deb done (we still need to sort out the automatic building of deb, but it's getting there).

We don't have rpm-lounge yet. Do we keep this ticket open, as it's quite vague and hard to tell when it's done, or do we create a new one for rpm-lounge? Tickets regarding the deb and arch ones can go in those repositories as well.

Thoughts?

**Comment by astorije** [comment]
Let's close this one, re-open if necessary.

As for rpm, if no one in the maintainers team is actually using it, it's harder to keep something properly documented, fully supported, etc. I don't recall people asking for an rpm, so let's see if it becomes highly-wanted and if someone from the community is ready to step up and officially maintain an rpm (just like @williamboman is doing for Docker and @maxpoulin64 is doing for Arch and Debian/Ubuntu).
