### ISSUE TITLE
Request: Support IPv6 servers

### ISSUE THREAD

**Issue by shinji257** [thelounge/lounge#431]
I might be formatting it wrong too so if this is actually supported I would like to know the proper formatting for it but it doesn't seem to support it.

When filling out the connection form ::1 results in EINVAL and [::1] results in ENOTFOUND.

**Comment by maxpoulin64** [comment]
As per [the node documentation](https://nodejs.org/api/net.html#net_socket_connect_options_connectlistener), it is supported but `family` needs to be specified which [irc-framework doesn't](https://github.com/kiwiirc/irc-framework/blob/master/src/connection.js#L84-L88). So it defaults to IPv4 and fails because of that.

**Comment by maxpoulin64** [comment]
Fixed in kiwiirc/irc-framework#55

**Comment by shinji257** [comment]
Ok.  I checked this out.  It is binding and accepting on both ipv4 and ipv6 for inbound listen but for outbound connect it will only do one or the other.  If you don't define it won't even try ipv6.  It defaults to ipv4 and stops there.  If you set a bind to ipv6 then it works fine with ipv6 servers.

**Comment by dgw** [comment]
kiwiirc/irc-framework#55 has to be merged and released in that upstream package on npm before connecting works as expected. The outbound connections are an issue in the dependency, not The Lounge itself.

**Comment by shinji257** [comment]
Yes.  I found this out in the irc room.  I applied the irc-fw PR locally so I can take advantage of it sooner rather than later. :wink:

**Comment by xPaw** [comment]
irc-fw has been merged.
