### ISSUE TITLE
Sending message to clear unread bar causes channel to disappear

### ISSUE THREAD

**Issue by MaxLeiter** [thelounge/lounge#468]
On iOS 9 safari and chrome

Send a message after checking a channel (when the unread marker is present). The channel (i.e. All messages) disappears until you switch channels/settings.

<img alt="example" src="https://sr.ht/EcnZ.png" width=200>

**Comment by maxpoulin64** [comment]
I can't reproduce on my side on latest master.

**Comment by omnicons** [comment]
My users currently encounter this issue on a clean master, on iOS 8 and 9

**Comment by astorije** [comment]
Let me ask something similar to #469 to help track down the bug.

It would be great if you could try with a few different commits (by simply running `git checkout <commit> && npm run build && npm start`). That way, we can figure out where the bug was introduced:

- https://github.com/thelounge/lounge/commit/b3d3582d2f83ce096daefa910ad55e779a95d41c Right before introducing the unread marker
- https://github.com/thelounge/lounge/commit/18c615236d18fc8bafd3d179f111355d961fce83 Right after introducing the unread marker
- https://github.com/thelounge/lounge/commit/faaa37cfe2b39c466df47aec9df403ea6c0a24c1 Right after refactoring a bit of our window management
- https://github.com/thelounge/lounge/commit/548a8d71308680d5b63b65512b7dabbc2ee4f974 Right after trying to fix a couple bugs introduced by some of the commits above

Feel free to report if you can say that for commit X the bug is definitely there, the bug is definitely not there, or you're not sure.

I can't reproduce on Mac OS X (desktop) + Chrome and I don't have an iOS around. It would be great if you could find a way to reproduce on desktop. Any help figuring this out is welcome :-) Thanks!!

**Comment by omnicons** [comment]
I'll include this in my testing tomorrow as I currently use an iPhone an
iPad and can try it out.

**Comment by omnicons** [comment]
So the commit b3d3582 definitely seems to be clear from the effects of the bugs introduced.
18c6152 Also seems to be clear, of this bug as well. 

faaa37c seems to be where this and other numerous graphical issues were introduced.

**Comment by MaxLeiter** [comment]
Can confirm this isn't on desktop, can't confirm if its on other small devices (tested on iPhone 6+ iOS 9.2)

**Comment by astorije** [comment]
@maxpoulin64, should we add the `urgent` label to this one? It's an important regression enough to prevent us to release a new version, IMO.

**Comment by maxpoulin64** [comment]
@astorije: sure. Will add to the other bugs as well.

**Comment by MaxLeiter** [comment]
This isn't present on master, but I can't confirm where exactly it was fixed. Would like if @omnicons also confirmed

**Comment by omnicons** [comment]
This doesn't appear to be present on master on the several devices I've been using it on. Tested on iOS 9.0.x 9.2.x and 9.3.x.

**Comment by astorije** [comment]
Alright, I guess this was fixed along the way then. Free win!

**Comment by astorije** [comment]
Alright, I guess this was fixed along the way then. Free win!
Thanks for the great help everyone!
