### ISSUE TITLE
New Messages Marker causes pages to not be scrolled to the bottom

### ISSUE THREAD

**Issue by omnicons** [thelounge/lounge#469]
I've just updated again to `master` and noticed that if my window fills up with text and I click away and people continue to talk, the window will stay where I last left off, hiding the New messages marker, and any new text until the buffer is scrolled down.

**Comment by astorije** [comment]
@omnicons, several things have recently changed that might affect this. Could you help us track down this issue please?

It would be great if you could try with a few different commits (by simply running `git checkout <commit> && npm run build && npm start`). That way, we can figure out where the bug was introduced:

- https://github.com/thelounge/lounge/commit/b3d3582d2f83ce096daefa910ad55e779a95d41c Right before introducing the unread marker
- https://github.com/thelounge/lounge/commit/18c615236d18fc8bafd3d179f111355d961fce83 Right after introducing the unread marker
- https://github.com/thelounge/lounge/commit/faaa37cfe2b39c466df47aec9df403ea6c0a24c1 Right after refactoring a bit of our window management
- https://github.com/thelounge/lounge/commit/548a8d71308680d5b63b65512b7dabbc2ee4f974 Right after trying to fix a couple bugs introduced by some of the commits above

Feel free to report if you can say that for commit X the bug is definitely there, the bug is definitely not there, or you're not sure.

Sorry about the extra work, but this is not something I could reproduce yet, and you would be the best to judge if the issue exists on these commits or not :-)

**Comment by omnicons** [comment]
Alright I'll do this tomorrow when I'm more awake and not busy with work!

**Comment by omnicons** [comment]
Alright so I've concluded my testing and managed to reproduce these issues here and on #468 
548a8d7 is where this bug is introduced.

**Comment by astorije** [comment]
Is this still an issue? I have never been able to reproduce this :/
