### ISSUE TITLE
Nickserv authentication

### ISSUE THREAD

**Issue by Fastidious** [thelounge/lounge#480]
Could services authentication be added? Thanks!

**Comment by maxpoulin64** [comment]
This problem is two-parts:

* SASL (preferred way) in #312 
* UI to request the user the information.

At the moment, it is possible to workaround this problem using the undocumented `commands` option. In your `users/<you>.json`, each network can have an array of commands that are sent as if they came from the client. So you can set something like `"commands": ["/ns identify <user> <password>"]` and you should be logged in before joining channels. Although #287 seems to say it is a bit buggy for now, but better than nothing.

Alternatively, you can also use the server password to login with NickServ on some networks (like freenode), but it doesn't work quite everywhere.

**Comment by Porco-Rosso** [comment]
Hi, Is there an example/explanation on how to configure the commands sent on connection?
I'm having trouble figuring out myself.

IMO this is something that should be included in the wiki.

**Comment by MaxLeiter** [comment]
I think it is documented somewhere - will check.

You can add a `commands: []` array into the network config (in the user json file)

**Comment by Porco-Rosso** [comment]
I get the `Socket error: Error: getaddrinfo ENOTFOUND adress adress:7000`
The same thing that seems to be described here: https://github.com/thelounge/lounge/issues/733 
I don't understand what I am doing that is wrong.

**Comment by mcdonalda1993** [comment]
> Alternatively, you can also use the server password to login with NickServ on some networks (like freenode), but it doesn't work quite everywhere.

How do you achieve this for freenode? I can't seem to get it to work

**Comment by xPaw** [comment]
`master` now does SASL authentication. However it still sends `PASS`.

**Comment by dideler** [comment]
FWIW, this is how I authenticated with shout before SASL became an issue. In `users/<nick>.json`
```
{
  ...
  "networks": [{
      "name": "Freenode",
      "host": "irc.freenode.net",
      "port": 6697,
      "tls": true,
      "password": "password",
      "nick": "foobar",
      "realname": "Foo Bar",
      "commands": [
        "/identify foobar password"
      ],
      "join": "#channel_a, #channel_b"
    }]
}
```

Is it now possible to auto-authenticate with SASL, and if so, how would the user config look?

**Comment by NinjaBanjo** [comment]
Any update on progress with this? There seems to be a note that sasl was broken in the framework being used, but it seems to have since been resolved. can we get documented support? that issues appears to have been resolved in december 2016

**Comment by xPaw** [comment]
SASL is supported, and `/ns` command can be sent using the `commands` array. So I'm going to close this issue.

**Comment by NinjaBanjo** [comment]
@xPaw Can you respond to @dideler 's question above? I have the same desire.

> Is it now possible to auto-authenticate with SASL, and if so, how would the user config look?

**Comment by xPaw** [comment]
Put the nick serv password in the server password field.
