### ISSUE TITLE
Autogenerate pem

### ISSUE THREAD

**Issue by ShenNoether** [thelounge/lounge#507]
It would be possibly nice to autogenerate the https keys on first start in private server mode, similar to how https://github.com/shennoether/mininodo works. If I get some spare time, will give a shot at coding it.

**Comment by astorije** [comment]
As in, self-signed certificate? If so, that would need to be an opt-in option!

I can't speak for anyone else, but personally I wouldn't want a system to generate its own private key + public self-signed certificate.
Maybe partially because I want to be in control of these things, but mostly because I'm proxying The Lounge behind nginx, which is in charge of the key management.
Also, I would (and do) prefer not using a self-signed certificate and go for one that is recognized by the browsers. With [Let's Encrypt](https://letsencrypt.org/), there are far less reasons not to do so :-)

Others, thoughts?

**Comment by ShenNoether** [comment]
Maybe a command line flag for it would be better? (Could also be such a flag to get the let's encrypt version)

**Comment by xPaw** [comment]
It's not our job to generate certificates. As for let's encrypt, that's perfectly suited for a plugin (which we don't support yet 😆)
