### ISSUE TITLE
Passwords as a per-user thing, not a per-server thing. 

### ISSUE THREAD

**Issue by AGausmann** [thelounge/lounge#509]
Original issue: https://github.com/erming/shout/issues/677

Nowadays a lot of IRC server and client software recognize the password field as something that a user uses to authenticate himself. For example, freenode forwards the PASS option to NickServ, and Kiwi allows the user to change the password field even when server connection settings are locked.

Shout/The Lounge currently handles the password field as a "network setting" as if the password is a mandatory field needed to access the network. In my opinion, and likely in the opinion of many others, the password field should be specified as a "user preference", not as a "network setting."

**Comment by maxpoulin64** [comment]
I have a bit of trouble understand what do you mean. Do you mean the password field should be moved down along with the nick and username? If so, while it is true that most of the time this is what happens, it is technically incorrect.

What we really need however is SASL username+password, which are the best way to authenticate with NickServ anyway. (And possibly also the custom commands)

**Comment by thisisdarshan** [comment]
+1 for SASL authentication

**Comment by TurBoss** [comment]
I modified my client.html to do this but if it could be by an option in the config it would be great
my config is lock server, hide network and per user password

**Comment by AGausmann** [comment]
I would be fine with the addition of SASL.

**Comment by xPaw** [comment]
Issue as is is invalid. SASL is supposed to be supported, by currently broken https://github.com/kiwiirc/irc-framework/issues/43

**Comment by nerthazrim** [comment]
Hi @xPaw !

Is this issue definitely closed?
I'm also using an IRC server that uses server password as user authentication, which means that I would love to be able to hide and lock network settings *except the password*.

Could you maybe add an option allowing your users to move the password block in the user settings (and not the password), if wanted?

A big thank for your amazing work!

**Comment by xPaw** [comment]
@nerthazrim You can keep the lock but display the network to allow setting a password. You're not gaining much by hiding the network anyway (if you really need to, you can do that by editing index.html or with css).

**Comment by nerthazrim** [comment]
True, I can display the network block but lock it, which works.
I was only hoping for a "sexier" option ;)

I used to do what you suggest with the 2.6.0: I edited index.html to move the password input in the user preferences block.
Since 2.7.0 however, I haven't found how to do it.
(And still, it means that I will have to re-do it at every update :) )

Not a big deal, I understand if you have more urgent requests. I thought that would be quickly implemented.

**Comment by xPaw** [comment]
If you want something done quickly, make a pull request yourself. Personally I don't see the need to move password field.

**Comment by nerthazrim** [comment]
I would if I knew how to do it, believe me ;)
My skills in JS are almost non-existent

I'll check if a friend is up to the task and can send you a PR, thanks for the answers xPaw!

**Comment by astorije** [comment]
@xPaw, regarding this, should https://github.com/thelounge/lounge/pull/2025/files#diff-e6a5b42b2f7a26c840607370aed5301aR513 also contain the password?
I'm unclear as to what this password does on the network, but I believe most people use it for network authentication.

**Comment by xPaw** [comment]
@astorije Adding it there won't do anything. Password field is still hidden on the client. Funny thing is that password is not enforced under `lockNetwork`, so it's just a failure of `displayNetwork` option. Technically only ip/port/tls fields should be hidden.

It's such a silly option too, I would recommend removing it and adding id or class attributes to each field on connect window so admins can hide them with CSS easily if they want to.

**Comment by astorije** [comment]
> Adding it there won't do anything. Password field is still hidden on the client.

I obviously meant to ask if the password should not be hidden as well.
Since it's not enforced by `lockNetwork`, then I think it should be displayed even when `displayNetwork` is `false`. In which case it does make sense to move it to the lower section IMO.

> It's such a silly option too, I would recommend removing it and adding id or class attributes to each field on connect window so admins can hide them with CSS easily if they want to.

That means for admins to hide network, it has to be done via a custom theme (and not providing other themes that display it). That's not ideal...
That said, I'm not against removing it, we just need to be prepared for riots :)
What use case does `displayNetwork: false` have?
