### ISSUE TITLE
Can't un-set /away

### ISSUE THREAD

**Issue by 73656e** [thelounge/lounge#518]
On 1.5.0 you can set yourself "away" using standard IRC "/away <message>" but sending an empty "/away" command doesn't un-set away like it's supposed to.

No errors or anything, just silently fails.

I only just installed The Lounge so still getting used to things, is there an error log or something I can paste to help figure this out?

**Comment by maxpoulin64** [comment]
We do not support the `/away` command. At all. So it's entirely dependant on the server.

The 2.0.0 prereleases probably handles this a bit better and likely at least prints an error message. We also display all unhandled messages in master, so that's even more progress. I would recommend trying the latest prerelease and report back (I'd normally recommend master, but it's a bit buggy right now).

**Comment by 73656e** [comment]
Cool. I wasn't so much expecting official support for the /away command, more figured that it would pass it along to the server raw, but it seems to be interfering/blocking it.

I'll wait for the update and see how it works on that. Thanks for the quick reply.

**Comment by vectr0n** [comment]
You can use "/quote away <message>" and "/quote away" to come back. Tested it on a few networks and it works as expected.

**Comment by xPaw** [comment]
@73656e we do not block or interfere with "unknown" commands, they are passed to the server as is. At least that's the case in the upcoming 2.0 version.
