### ISSUE TITLE
Disable whois/messaging users when clicking their nicks

### ISSUE THREAD

**Issue by zachbr** [thelounge/lounge#533]
This is a UX change request, not a critical feature, however it is one of those "slight annoyance" things.

Clicking on a user's nickname should not open a new tab with their whois information. This is only slightly annoying on desktop, however on mobile it is infuriating. I would much prefer a more traditional, and much more explicit, context menu option to whois/message them, rather than just a single click, which seems a bit unexpected at best.

Thanks, enjoying the lounge overall.

EDIT: even an options toggle or something, just some acknowledgement that this may not be the best design. Nor should it assume I want to whois people. Why not autofill their name? or do nothing at all?

**Comment by metsjeesus** [comment]
This is one of the small things what might need huge overhaul on system to fix it. I might be wrong though.

You can remove whois command, but after that it wont open private channel. Problem is, every channels has some ID on it, so client and server can figure out on what channel they exchange messages. So to create channel,  you have to initiate it somehow. Moment you either send whois, a message or get a private message to create a client-server pair of a channel. Whois does not send usually anything to the target channel, so they keep using it.

How to fix? Because channel is paired with a ID in client and server, you need to emit a message what does not push any IRC commands trough. Moment it seems this type of messages wont exist yet and probably needs huge overhaul to do it.

**Comment by maxpoulin64** [comment]
It would actually be relatively easy to add, it's just currently not worth the time as we're busy on much more important things. PRs totally welcome to fix tho, we already have context menus in place. It's about just a matter of adding a command for it.

I'm not sure why people are annoyed by the whois tho. It doesn't hurt, just gives you a bit of info in the window but that's it. It's easy to ignore. I find it cool to be greeted with the person's details when opening a PM window.

**Comment by Zbob750** [comment]
I don't really even want it to open a PM window, or do anything. Which is half of the issue.
May look into this at some point, but I'm not very familiar with the way this is written, or JS at all.

**Comment by metsjeesus** [comment]
Imagine you got 2 interfaces to the same client, web and mobile. Generally you want to sync them up, so any action on either of those interfaces will be trasfered to all of them. Clicking on username moment is done with a easy solution. Clicking username send whois command to node server, what sends whois command to irc, gets result back and sends result to every interface connected. Works. 

So if you got 2 interfaces, what should happen on clicking on nicks? Because channels are saved in node server, should it create private channel on every interface? That means if you click on web interface on a nick, it creates channel in web interface and in mobile interface?

Or maybe do it nonsync way. Clicking nickname creates channel only on that interface. Node server wont get any data of it. That means if you click on web interface on a nick, it creates channel only on web interface and its ignored on mobile interface. Only if actually data is sent or recieved, it should create the channel on interface. 

Personally I think latter one is the way it should be. Problem is, currently all the channels are identified with a id, not by channel name. So its needed to create a id pair in both in interface and on node server. To change it, all the id based identificators need to change name based identificators. And that is a bit bigger overhaul then simple fix.

**Comment by astorije** [comment]
This was addressed by #1722 🎉

**Comment by zachbr** [comment]
Awesome, thanks everyone
