### ISSUE TITLE
Channels with capital letters are sorted at the top

### ISSUE THREAD

**Issue by PugaBear** [thelounge/lounge#571]
When I connect to a znc bouncer, the channels with capital letters are autosorted to the top. Obviously this shouldn't be the case.

![hello there](https://cloud.githubusercontent.com/assets/12417961/17781182/e41c35ee-6533-11e6-8b85-da7a4a974ef0.png)

**Comment by YaManicKill** [comment]
Yeah, this is basically down to how characters are ordered.

Example:

> "Z" < "a"
> true
> "a" < "b"
> true

So, basically it goes through A-Z and then a-z.

**Comment by dgw** [comment]
Poking around from my phone, I'm having trouble finding where the channel sorting occurs. But surely there is a way to substitute a case insensitive sorting function?

**Comment by astorije** [comment]
@dgw, it's... awkward to say the least. I looks like [this](https://github.com/thelounge/lounge/blob/36a21bacac6b0d3231b152f9df1f1655fdf62c78/src/client.js#L390-L404) is a place where we would do channel sorting, but to be honest I'm not entirely sure that function does any sorting at all.

I don't use ZNC so I'm not too sure but is there any chance ZNC itself could be providing us with a list of channels to join already sorted that way?

**Comment by PugaBear** [comment]
I don't believe that's the case, it sorts them correctly on my phones client (AndroIRC) and HexChat

**Comment by dgw** [comment]
ZNC actually has its own issue(s) open for channel join order/sorting (znc/znc#104, znc/znc#238).

**Comment by xPaw** [comment]
Unless I am mistaken, lounge does not do any alphabetical sorting on channels. When channels are joined, they are appended to the bottom of the list. The `client.sort` method is for manual sorting (e.g. dragging channels). Since you use znc, I believe that's where sorting issue comes from. However, I think lounge user's sorting should persist even on top of znc connections (it does for me on master).
