### ISSUE TITLE
NPM Install "Killed"

### ISSUE THREAD

**Issue by spencerthayer** [thelounge/lounge#579]
```
.../lounge$ npm install

npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
\
> dtrace-provider@0.6.0 install /var/www/lounge/node_modules/ldapjs/node_modules/dtrace-provider
> node scripts/install.js


Killed
```

**Comment by YaManicKill** [comment]
It'll probably be your OS killing it. NPM uses a lot of ram, and if you don't have any swap space defined, and the RAM gets filled, npm will be killed.

This is something I have found on a lot of default servers, that they don't have any swap defined (because a lot of them will be running on SSDs).

Either way, this won't be a bug with us, if anything it'll be an npm bug. But try swap space and see if that helps.

**Comment by spencerthayer** [comment]
Incidentally can two instances of Lounge run under two different user accounts on different ports?

**Comment by YaManicKill** [comment]
Not directly, because they both use the same config directory. You could easily modify the code to do it, though.
