### ISSUE TITLE
Slow quit after closing browser tab in public mode

### ISSUE THREAD

**Issue by TurkDesk** [thelounge/lounge#581]
Closing the tab browser should quit you from irc right away for public mode but it seems takes long here are some logs that closed browser tab after join but it takes up to one min to quit from irc.

(18:42:23) \* lounge-user (lounge-user@42812E.953EC3.CE8F25.AEE6D1) has joined #mytest
(18:43:49) \* lounge-user (lounge-user@42812E.953EC3.CE8F25.AEE6D1) Quit (Quit: Reason filtered)

(18:44:13) \* lounge-user (lounge-user@42812E.953EC3.CE8F25.AEE6D1) has joined #mytest
(18:45:38) \* lounge-user (lounge-user@42812E.953EC3.CE8F25.AEE6D1) Quit (Quit: Reason filtered)

**Comment by maxpoulin64** [comment]
Quick guess might be that socket.io was using the polling transport, so possibly a whole second of delay to let the browser ping back? It's pretty much instant for me when using websockets.

**Comment by astorije** [comment]
That's more than a minute though, far from a second 😕

**Comment by astorije** [comment]
This issue is fairly old and none of us have encountered it. If this was an actual issue, it is likely that it was fixed since then or that it came from a dependency / OS thing.

I am closing this for now, let us know if the latest version of The Lounge (or `master` which has a lot of extra changes) is still affected.
