### ISSUE TITLE
Tooltips do not hide on mobile after clicking the underlying button

### ISSUE THREAD

**Issue by astorije** [thelounge/lounge#585]
Asking for a friend

> @xPaw:	Lul, sending a message on mobile leaves "send message" tooltip
> @williamboman:	Yeah tooltips should be disabled altogether on handheld devices
> @xPaw:	They should not
> @xPaw:	They appear when holding, which is good
> @xPaw:	Same thing happens with user list icon, maybe the click events are cancelled
> ...
> @MaxLeiter:	On mobile the user-list and send message tool tips stay visible after tapping them, not too useful :(
> @MaxLeiter:	Actually, all icons with tool tips (settings too, for example)

Turns out, when looking at an instance not running #540, bug was there already on Connect/Settings/Logout buttons, but we wouldn't notice it because clicking on them hides the parent object (the sidebar).
It might be a bug with [Primer's tooltips](http://primercss.io/tooltips/)...

Help welcome.

**Comment by YaManicKill** [comment]
Soooo, this is because they probably aren't designed for buttons. 

[In the code](https://github.com/primer/tooltips/blob/master/lib/tooltips.scss) you can see that it does it on focus as well as hover, which is what makesi t work on mobile. So, we have 4 possible ways of moving forward:

1. Remove the focus option. This will stop the tooltips working on mobile, probably (as hover doesn't exist on mobile).
2. Shift focus to something else after the buttons are pressed (for the send button, that would be the input, which would solev a second problem about the keyboard disappearing when you click the send button, but what would we do for the others?)
3. Show the tooltip when we long press the buttons on mobile. Probably not ideal...and would require JS, which is kinda defeating the purpose of having a CSS only version
4. Just go back to bootstrap tooltips, or some other solution that isn't CSS only.

**Comment by astorije** [comment]
> Soooo, this is because they probably aren't designed for buttons.

GitHub uses them on buttons though, so it should be fine...

> Shift focus to something else after the buttons are pressed (for the send button, that would be the input, which would solev a second problem about the keyboard disappearing when you click the send button, but what would we do for the others?)

That's a tricky thing as we need to remember to move focus after every press on everything that has a tooltip. Also, depending on how this is done, it can be terrible or really good for accessibility: when opening a context menu, it makes a lot of sense to focus the first item in the list, but in other situations, this can be very confusing for a keyboard/screen reader user.
EDIT: I just noticed the context menu button does not have a tooltip, so whatever lol

Regarding the input/send button, there was an attempt in #483 but seems to be failing hard on Android (auto-select an empty text!!).

There might be something we can do that would be a mix of 1 and 3.
I'll try to play with this when I have a bit of time, but that might not be before a couple weeks or more, so I'm leaving the `up for grabs` label on. In the meantime, do you see this as a blocker for 2.0.0?

**Comment by YaManicKill** [comment]
I do not think this should be a blocker for 2.0.0. It's a minor issue. 

> GitHub uses them on buttons though, so it should be fine...

Does github use this library?

> That's a tricky thing as we need to remember to move focus after every press on everything that has a tooltip. 

Yeah, I'm not suggesting it's a good fix, but it might be a hacky workaround we can use ...

**Comment by astorije** [comment]
> Does github use this library?

Yep, Primer is their library, and they use it extensively in their products.
