### ISSUE TITLE
lounge reset - reset password command requires a server restart.

### ISSUE THREAD

**Issue by amcgee7** [thelounge/lounge#598]
In testing the tools for lounge.  The 'lounge reset' command does change the hash in the json file for the user but the password change doesn't take effect until the server is stopped and started again.  I've noticed in the clientManager.js that it checks for users being added or removed but from what I can tell it doesn't check for changes in the json file.

**Comment by amcgee7** [comment]
After a number of code changes I decided to use a workaround. I remove the json file and then move it back and that seems to work.  I'm otherwise unsure how best to fix this issue.

**Comment by astorije** [comment]
Ouch, good catch, this is nasty. This also has some security implications because resetting on the server side is rather an admin option, so potentially trying to lock someone out...

I believe the clean solution would be the same as the one describe at https://github.com/thelounge/lounge/issues/447#issuecomment-246565254:

> So until we do proper file/directory watching on new or changed files (something like [this](https://nodejs.org/docs/latest/api/fs.html#fs_fs_watch_filename_options_listener) or better), there is nothing we can do to get rid of this IMO.

What do people think?

**Comment by astorije** [comment]
#751 implements such file watching so I believe this is now possible (additional comment by @xPaw at https://github.com/thelounge/lounge/pull/779#issuecomment-265508333).
