### ISSUE TITLE
Unread marker shows up incorrectly when joins/parts are hidden

### ISSUE THREAD

**Issue by nornagon** [thelounge/lounge#604]
To reproduce:
1. Hide joins/parts
2. Join a channel
3. Wait for someone to join/part
4. Observe 'New messages' marker appears, despite there being apparently no messages in the channel.

![_the_lounge](https://cloud.githubusercontent.com/assets/172800/18457572/ccdf6c22-790e-11e6-8ea2-1d0eb8b6348f.png)

**Comment by astorije** [comment]
Yes, this is definitely a bug.

Issue is that unread marker is being hidden with CSS when it's the last element of its parent. When there is (for instance) a join and joins are hidden, marker is not considered last child even though it appears to be so.

I'm not sure there is a way to hide "last-child-but-not-really" directly in CSS. I can't think of anything (tried a few using `.unread-marker:not(...):last-child` without any luck) right now.
Curious what @xPaw would think about this.

**Comment by xPaw** [comment]
@astorije this can't be fixed in pure CSS. The simplest fix I can think of is checking if unread marker is the last visible element whenever appending received messages to the DOM.

**Comment by nornagon** [comment]
IMHO the easiest way to handle this is to just not render hidden messages instead of annotating them with `display: none`. If the UI code were driven from state, it'd be simple to add/remove those messages from the DOM as necessary :)

**Comment by astorije** [comment]
> @astorije this can't be fixed in pure CSS. The simplest fix I can think of is checking if unread marker is the last visible element whenever appending received messages to the DOM.

Agreed re: CSS. Regarding your solution, I'm not sure how this could work but I might have misunderstood. I think any solution would need to check if specific joins/parts/etc. are enabled or not and moved the marker or not depending on that.

> IMHO the easiest way to handle this is to just not render hidden messages instead of annotating them with display: none. If the UI code were driven from state, it'd be simple to add/remove those messages from the DOM as necessary :)

This is far from the easiest way as pretty much everything in the client is tied to that idea of having unwanted messages hidden in CSS instead of not being part of the DOM.
That being said, I am not against that solution at all, but keep in mind that it's a bit closer to a refactor than a solution :)
@xPaw, thoughts on this?
