### ISSUE TITLE
Completely remove the hover-appearing close button in channel list

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#61]
Discussion continued from #48:

> Just a thought, what if he got rid of that close button completely? It would avoid accidentally clicking it while trying to focus the channel. There's already a dedicated Leave button when channel is in focus, and #9 adds a way to close channel in a context menu.

**Comment by YaManicKill** [comment]
I, personally, would be strongly for this. Especially when we get the context menu.

**Comment by YaManicKill** [comment]
Context menu now merged. I'm in favour of this now. Others?

**Comment by dgw** [comment]
Eh, I just used them several times tonight to reset my ZNC channel filters with the new client ID I set.

FWIW I had icon issues earlier and the close buttons appeared to be gone, so I had to leave a few channels with the Leave button. That was tedious, and a context menu would be the same number of clicks.

Still in favor of moving them to the left side of the list items.

**Comment by xPaw** [comment]
@astorije, @maxpoulin64 what's your opinion on this? We now have context menu, and a separate Close button when the channel is active.

**Comment by lindskogen** [comment]
I would vote for removing it. We have `/part` and the leave button in the corner already

**Comment by maxpoulin64** [comment]
I guess I can live without it. It's not like I part channels all day long anyway. I think it's kinda sad to remove it just because people can't aim but whatever fits with the majority.

**Comment by dgw** [comment]
> I think it's kinda sad to remove it just because people can't aim

This. At this point I feel like I'm repeating myself a lot, so this will be the last time I say: Move it to the other side and it will be fine.

**Comment by YaManicKill** [comment]
Its not about aiming. Its about the fact that it isn't there until you go
over the list, and if you click as soon as you put your mouse on a list (as
is quite common) then you accidentally close it.

It is very bad affordance.

I would be alright with moving it to the other side and make it always
visible. But to have it only appear when you hover over it is what causes
the problems.

**Comment by astorije** [comment]
> I guess I can live without it. It's not like I part channels all day long anyway. I think it's kinda sad to remove it just because people can't aim but whatever fits with the majority.

I agree with that, sad for this reason, and also because it's a part of the original UI that I felt fit very well in the app. But oh well.

I note however that I have seen this in many chat applications, including Slack, and it never stroke me as a UX issue.
I will ask the UX lead of my day job to have his external opinion, but I think I'm OK with that change.

> Move it to the other side and it will be fine.

It won't be. Making it always visible would be horrendous for the nice UI we currently have, and not making it always visible would simply translate the issue: should it appear between the icon and the text, and move the text every time? Should it replace the channel icon when hovering? Should it go on the far left of the channel icon, in the margin? All these options have issues.

**Comment by YaManicKill** [comment]
> I note however that I have seen this in many chat applications, including Slack, and it never stroke me as a UX issue.

Wait, what? Slack doesn't have this. 

Firefox used to, but they changed it. Now they have an always showing X on just the selected tab. Chrome shows X always. Slack doesn't have any X. I don't know of any apps that have an X on hover.

The fact of the matter is, it does confuse people. We had several people talk in shout about how they have issues with it, I still sometimes have issues with it. You just forget it exists because it's not visible, and every few weeks I close a chat accidentally because of it.

**Comment by dgw** [comment]
> I don't know of any apps that have an X on hover.

Safari does. TIL Apple doesn't know about affordances.

> You just forget it exists

I don't. I depend on it to be there when I want it (on hover) and not to clutter the layout otherwise.

**Comment by YaManicKill** [comment]
> The Lounge could have a short Undo period for parting a channel, like Gmail does for archiving/labeling/deleting a conversation, if it's really that big of a deal.

Yeah, we discussed that. And although it's a good plan, it'll be quite a bit of work.

**Comment by lindskogen** [comment]
Just delay the action on client side with a `setTimeout`? Shouldn't be that hard

**Comment by YaManicKill** [comment]
Well yes, but you also have to have a way to cancel it. I'm not saying it's hard, but to make sure it works fine would involve a bit of work, especially having a nice way to cancel the removing.

The thing is, even if we have that, I still fundamentally disagree with the invisible close button until you hover over it. Having an undo is just having a sticking plaster on the issue rather than solving it.

**Comment by astorije** [comment]
> Wait, what? Slack doesn't have this. [...] Slack doesn't have any X.

Not for channels, but for direct messages, that are listed right below the channels:

![slack_close_btn](https://cloud.githubusercontent.com/assets/113730/13694232/64f17350-e721-11e5-9a7e-7e3c2d3dd512.gif)

The fact that you never noticed it shows me how unimportant this can actually be :D (that or you don't use direct messages, only channels).
Anyway, not trying to argue actually, because I agree with you :-) I just wanted to show my example.

> Firefox used to, but they changed it. Now they have an always showing X on just the selected tab. Chrome shows X always.

(Note that Chrome behaves similarly to Firefox when you have lots of tabs.)
Now that's interesting. I have discussed with a UX lead today, and he ended up suggesting this as his preferred solution, which I believe would work very well: only show the <kbd>&times;</kbd> on the active channel/private discussion (like you mention on Firefox, actually). That way:
- It works on mobile, no hover anymore.
- It prevents wrong clicking as you would not be able to close it clicking it first.
- It keeps a nice, slick UI.
- We can get rid of that ugly Disconnect/Leave/Close button (hate to have multiple names for something that has the same result to the user) that does not even match other button styles (Settings cog, user list, ...).
And we can still close a chat without entering it using @xPaw's context menu.
I personally very much like this idea, which we can refine later anyway.

I foresee some people will be against removing the Leave/Disconnect/Close button because they are used to it, but I believe its location in the topic bar and UI are confusing at the moment: if we remove it, it's gonna be a matter of getting used to closing a chat in the sidebar instead of the top-right corner :-)

@YaManicKill, what do you think? I believe that would solve your initial issue, and rather elegantly IMO.

> Just delay the action on client side with a `setTimeout`? Shouldn't be that hard

Actually, it's more than that. Say you set a 30-second timeout for actions that need it in such way: what happens if you close the chat within these 30 seconds? Or if the device hangs?
This sort of features, while they seem trivial and no-brainers, are actually difficult to design right, and easy to design poorly.
Add to that that our client is clunky vanilla JS + jQuery, and that it's evolving a lot, I can tell this is gonna be a feature we break often. If we were using frameworks such as React+Redux, that offer simple ways to do time traveling, and also to have a test suite ensuring we don't regress, the story would probably be different, but that's not the case here. Also...

> Having an undo is just having a sticking plaster on the issue rather than solving it.

... That!
Relying on an undo to fix a usability issue is not desired. I would compare that to adding countless settings to try to offer solutions that please every personal habit instead of making choices justified by discussions, pros/cons, deliberations, UX patterns and user-centric, ...
If we ever have an Undo button, I'd argue it should ideally undo an action a user has change his mind about rather than an action he made by accident too many times :-)

Sorry for the novel, I had a lot on my mind!

**Comment by xPaw** [comment]
@astorije Displaying `x` on active windows is actually not a bad idea

**Comment by YaManicKill** [comment]
I would be fine with only displaying it on active windows, that sounds fine. And the context menu does allow you to close ones you are not in.

> The fact that you never noticed it shows me how unimportant this can actually be :D (that or you don't use direct messages, only channels).

I hardly ever use slack, I just had it opened and went to have a  look and didn't see them :stuck_out_tongue:

**Comment by richrd** [comment]
Showing <kbd>x</kbd> only on active windows is a brilliant idea. The best of both worlds :+1:
