### ISSUE TITLE
Doesn't load on LTE

### ISSUE THREAD

**Issue by RichusX** [thelounge/lounge#642]
I'm unable to login to the lounge from a mobile network because receiving the javascript needs to be enabled message even though it already is. It works fine on wifi and it used to work fine with version 1.5 but doesn't anymore on 2.0.

Screenshots:
http://imgur.com/a/NGUdu

**Comment by MaxLeiter** [comment]
Doesn't happened to me on iOS, and I know plenty of people use android with LTE, so I think it's a more specific problem. Are you running from source or npm?

**Comment by RichusX** [comment]
npm

**Comment by RichusX** [comment]
I've tried re-installing but that didn't fix it

**Comment by MaxLeiter** [comment]
Can you enable remote debugging and take a look in the inspector?

**Comment by xPaw** [comment]
Does it work in a desktop browser? If so, could you try USB debug to see the errors or anything?

**Comment by Gilles123** [comment]
Random thought, but can you try running it on a different port? I know some carriers block certain things (some even block IRC servers outright), and port 8080 is a standard port for HTTP proxies, so they may be doing something there.

**Comment by RichusX** [comment]
LTE:
![Remote Debug LTE](http://i.cubeupload.com/yavI7O.png)

WiFi:
![Remote Debug WiFi](http://i.cubeupload.com/yavI7O.png)

**Comment by RichusX** [comment]
@Gilles123
Running on port 8888 and still getting the same issue 
![Running on port 8888](http://i.cubeupload.com/CCEc1L.png)

**Comment by xPaw** [comment]
I just loaded your lounge instance on LTE and it's fine. Sounds like a problem with your mobile setup. Try a different device.

**Comment by astorije** [comment]
It does seem like either your mobile or your LTE provider is injecting something to the page. I mean, [that wouldn't be the first time a carrier tries to do something like that](https://www.wired.com/2014/10/verizons-perma-cookie/). What's your carrier?
Funnily, that's kind of what our CSP tries to prevent, but we'd expect that kind of injection coming from the outside...

CSP was added in v2.0.0-pre.1, so it's likely that the underlying issue is still present in 1.5.0, but we don't attempt to protect the app from it there.

I am closing this issue as this is not related to The Lounge but to either your phone or your provider, but feel free to continue discussing if you find something new.
