### ISSUE TITLE
A proper structure for the client javascript code

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#66]
Currently most of the code is in a single file with a lot of anonymous functions. Anon functions make it harder to debug/view stacktraces when analyzing stuff. Having a neat structure where each element is in a separate namespace/scope would be preferred.

**Comment by astorije** [comment]
I reckon @YaManicKill was interested into making this a reality too: https://github.com/erming/shout/issues/612

**Comment by YaManicKill** [comment]
Yeah, I would like to modularise it. @MaxLeiter's work on #62 is going to help that a lot, as the structure will already be there, and we can then just abstract parts out and organise the code in a way that makes it really easy to find specific features (for example, it's really hard to find where ... say the settings code is).

**Comment by nornagon** [comment]
I'm interested in this :) See #610

**Comment by astorije** [comment]
Now that Webpack has landed, can we discuss the structure we want for the client code here before making any drastic change?

Any suggestion?

It seems very appealing to split per component (message input, chat window, user list, user search, etc.) but that's very high level. How do we want to apply this in practice?

**Comment by YaManicKill** [comment]
I think splitting based on functionality is a good way to do things. This would kinda work with what you are doing, but also allows us to split out other things similarly (settings can be it's own, one for the new code I've written for message condensing etc). But it's not as simple as define exactly how we split things out. It's hard to generalise it without actually just doing it. 

However, I don't think we should do a big bang approach of "remove all the things into other files" because that'll get nasty.

Instead, we should move code out as we change it. For example, next person to do the settings code could move that out to a module, (which is a better way to deal with settings as it means it's easier to change out how we are saving the settings without changing other code, etc, etc).

Does that make sense?

**Comment by astorije** [comment]
> Does that make sense?

Definitely, but I would like to discuss the structure (like, folder structure) here before someone actually univocally decides to do it.

**Comment by YaManicKill** [comment]
> I would like to discuss the structure (like, folder structure) here before someone actually univocally decides to do it.

Sure, well yeah, if you want an example of what I was suggesting, I would make module structure for some of it like this:

> settings.js
> input.js
> contextMenu (this makes sense to split into different ones depending on which you are clicking on, maybe with an index.js that would include some common code between them? Not sure yet)
  > userMenu.js
  > chanMenu.js
> channelList (I reckon we'd have a couple for this, because there are a number of things to do with it)
  > display.js
  > sorting.js

Does that make sense as a structure?

**Comment by MaxLeiter** [comment]
Can this be closed?

**Comment by YaManicKill** [comment]
Yeah, it isn't fully finished, but it never will be. We are in a good place now.
