### ISSUE TITLE
Can't move channel to bottom of list.

### ISSUE THREAD

**Issue by DaneEveritt** [thelounge/lounge#668]
Running the latest build I cannot move a channel in the channel list to the very bottom position.

The only way to put it down there is to move it to the second-to-last slot, and then move the last channel in the list up one. When I try to drag it to the bottom it just sits on top of the last element.

Safari Version 10.0 (11602.1.50.0.10)

**Comment by xPaw** [comment]
Duplicate of #494

**Comment by astorije** [comment]
That's not *exactly* the same problem, but the cause is most likely the same. Drag and dropping to the last position works fine, except when bug described in #494 appears and then it's not possible to drag and drop last anymore.
I would love to fix that issue, but didn't find time to research it yet.
