### ISSUE TITLE
webirc

### ISSUE THREAD

**Issue by sirx** [thelounge/lounge#688]
There is no documentation on how to set up the webirc correctly.

Would be very nice to know how.

The other issue oepnend about this topic wasnt helpful aswell I did this and now my config is broken.

**Comment by maxpoulin64** [comment]
```js
webirc: {
    "irc.example.net": "YourPassword"
},
```

Where `YourPassword` is the password that the administrator of the ircd gave you. That's it. That's litterally all there is to it.

If you are said administrator, then you will have to read the documentation of your ircd to know how to set up cgiirc/webirc for that particular ircd.

**Comment by sirx** [comment]
I guess the IRC Admin has set up this I want to know how to edit the thelounge config to get it working

**Comment by maxpoulin64** [comment]
Can you detail a bit more which part you are having trouble understanding? I'm not sure I get what part is problematic...

**Comment by sirx** [comment]
`// WEBIRC support
//
// If enabled, The Lounge will pass the connecting user's host and IP to the
// IRC server. Note that this requires to obtain a password from the IRC network
// The Lounge will be connecting to and generally involves a lot of trust from the
// network you are connecting to.
//
// Format (standard): {"irc.example.net": "hunter1", "irc.example.org": "passw0rd"}
// Format (function):
//   {"irc.example.net": function(client, args, trusted) {
//       // here, we return a webirc object fed directly to `irc-framework`
//       return {username: "thelounge", password: "hunter1", address: args.ip, hostname: "webirc/"+args.hostname};
//   }}
//
// @type     string | function(client, args):object(webirc)
// @default  null
webirc: null,`

I don't know what to do there

**Comment by maxpoulin64** [comment]
Just use what I pasted above (which is the standard option from the documentation you quoted).

The remaining is a second, more advanced way of doing webirc that gives you full control over what is passed in. But that's totally optional, and only needed if you want to customize the hostname and IP of the user to fake, predefined values.

The standard (and easy way) is just a pair that says "this server" requires "this password", and Lounge will simply pass on the real IP and hostname of the visitor just as if they connected using a standard IRC client without the need of any additional configuration. Unless you want to do stuff like Freenode and set something like `gateway/web/xx.xx.xx.xx` (which ideally, should be done on the ircd side anyway), this will very likely do exactly what you want out of the box.

If you do still want the advanced version... Well you'll unfortunately need to learn a bit of Javascript, because it's a Javascript function that's run for every connection where you have to build the webirc configuration object yourself. There's no preset there: you have raw access to everything. The return values are fairly self explanatory:

* username: that's the webirc username sent to the server
* password: that's the webirc password sent to the server
* address: that,s the IP address sent to the server. The ircd will think the user is connecting from that IP and will blindly trust this.
* hostname: the hostname that will be sent to the server, which again is blindly trusted.

Does that help?

**Comment by sirx** [comment]
I will try it out, thank you very much for helping me!

I am very thankful

**Comment by maxpoulin64** [comment]
Do you have any suggestion as to what I could add to the default config to better explain this? I thought it would be fairly clear that there are two ways, and that most people would just use the first one unless they understand the second one and have very good reasons to bother with it.

But I also have been into programming for half my life now, so my ability to see this in the perspective of a non-programmer is pretty much gone :/

**Comment by sirx** [comment]
What always helps very good is a quick line saying: 

// EXAMPLE
//webirc: {
//   "irc.example.net": "YourPassword"
//},

This would have helped me a lot for example :>

Btw I got it running, and I love it.
