### ISSUE TITLE
Allow custom themes from outside the lounge folder

### ISSUE THREAD

**Issue by MiniDigger** [thelounge/lounge#728]
whenever I update lounge I need to upload my custom theme again, which I feel is unnecessary.  would it be possible to not delete custom themes?

**Comment by xPaw** [comment]
Do you mean in `client/themes/` folder or the custom css box?

**Comment by MiniDigger** [comment]
the themes folder.

**Comment by xPaw** [comment]
npm would be doing that, I'm not sure we can fix it easily. The proper way would be to have a `themes/` folder in the users' config folder so that it's outside the installation.

**Comment by astorije** [comment]
FYI I attempted this in https://github.com/thelounge/lounge/tree/astorije/themes-path but then gave up as it was harder than I thought. I'll probably get back to this someday but until then, you're kinda stuck... (unless there is a way to tell npm to keep unknown files around but I don't think that's possible)

**Comment by YaManicKill** [comment]
@astorije Can you remember what the issue was with that branch?

**Comment by astorije** [comment]
Mostly, themes existing in 2 places makes it not obvious to select a theme from the UI. First step is to figure out a correct organization. Does that make sense?
EDIT: Actually, it surely does because I just saw #1228. It's a bit too late for me to get involved in it right now, but I will definitely share my thoughts there (unless we share the same ones, which is not impossible!) and get back to you.

**Comment by YaManicKill** [comment]
I have edited the name of this to make it more clear how we are going to come out of it. We have a PR up, #1266, for allowing themes via npm, which is nearing completion, and this issue will be closed when that happens.

**Comment by compuguy** [comment]
So how would this play out if your using the provided docker image? @YaManicKill

**Comment by astorije** [comment]
This is resolved by #1266 🎉
