### ISSUE TITLE
Feature request - Add configuration option to enable/disable user-defined CSS style

### ISSUE THREAD

**Issue by zeten30** [thelounge/lounge#735]
Would it be possible to add configuration option to enable/disable user-defined CSS style? In some cases, it might be considered as not 100% secure to allow user to load his own code into application. This might be useful for public Lounge deployments. Users can ask administrators to create/modify pre-defined styles instead.

**Comment by zeten30** [comment]
Or another reason might be protecting non-technical users from breaking their environment.

**Comment by maxpoulin64** [comment]
You can easily remove it from the source code, or hide the box in your theme.

This may sound insecure or cheap, but the truth here is that every browsers lets you put your own CSS and script however you want by simply pressing F12. Therefore, right at the moment they can unhide the box, they essentially already have the functionnality that the box provides.

Additionally, the custom CSS option, along with all other settings, are stored purely on the client in local storage. They never hit the server. Custom CSS is only a risk for the user that enters it in their own client. On top of that, CSS is only styles. The worst a user can do with it is screw the page layout, which is fixed by adding `?nocss` to the URL.

So, yeah, I think just hiding it in a theme is plenty enough.
