### ISSUE TITLE
Date separator (and new messages bar) shows on new query with use

### ISSUE THREAD

**Issue by MaxLeiter** [thelounge/lounge#771]
![image](https://i.imgur.com/Leo4EsZ.png)

Both should probably not show

**Comment by stepie22** [comment]
Hmm, I specifically add a date-marker when opening a channel/query because for me that makes sense, otherwise the first time you message someone/join a channel, there would be no date-marker. I won't argue against removing it though if people think it should be removed.

I agree that the new message marker probably shouldn't show up if you started the query though.

**Comment by YaManicKill** [comment]
I'm not sure the issue?

The date marker is fine for @stepie22's reasons, and it is a new message, isn't it? So the unread marker would make sense as well.

**Comment by xPaw** [comment]
Yeah this is not exactly a bug. Whois info comes after the windows is open, thus the messages are new.

**Comment by YaManicKill** [comment]
Alright, closing then. @MaxLeiter If you really think it's an issue, re-open and suggest what you would prefer, but I think this is fine.

**Comment by MaxLeiter** [comment]
I felt it was an issue because you "create" the Whois messages and it felt cluttered, but not a big deal
