### ISSUE TITLE
Hide ranks without search match

### ISSUE THREAD

**Issue by PugaBear** [thelounge/lounge#774]
![image](https://cloud.githubusercontent.com/assets/12417961/20856358/640e5c68-b8d2-11e6-8b30-655b2cb00489.png)

Simply remove the rank headers from view when there's no search matches.

**Comment by iamsk9** [comment]
can i contribute to this issue?

**Comment by xPaw** [comment]
@iamsk9 sure.

**Comment by iamsk9** [comment]
@xPaw   Does this issue mean to hide the rank headers in the search bar on the right side of the application when no search matches? if yes it is working well and no rank headers are shown when there's no search matches.

**Comment by xPaw** [comment]
It should hide the section if there are no matching users in that section (this could be used as an optimization trick too, hide the entire category instead of hiding every individual user inside).

**Comment by iamsk9** [comment]
@xPaw  ok I got it.

**Comment by GiacomoCaruso** [comment]
@xPaw I fixed the issue, but I don't see how it's possible to optimize it as you wrote. In order to check if there are no matching users, you still have to loop through all of them. If you don't hide the users that don't match while you loop through them the first time, you'll have to iterate through all of them (or at least the ones to hide, which usually are most of them) again in order to hide them. Shall I open a pull request with my solution or do you have any suggestions about how to optimize it? What I have done, essentially, is to loop through each category of users (class: user-mode), then nested loop through each user of each category. If all the users of a category are hidden, then I hide also the div of the category.

**Comment by MaxLeiter** [comment]
I think xPaw meant you can set the parent (assuming that sections are wrapped in a parent element) to hidden instead of setting every name to hidden (less DOM modifications)

**Comment by GiacomoCaruso** [comment]
Ok, I understand. I am working towards a more performant solution. I should finish it in the next few days, hopefully already tomorrow. It's my first contribution ever, I will do my best to make it decent :)

**Comment by MaxLeiter** [comment]
Feel free to open a PR early (it can be marked as 'do not merge'/'wip') for feedback/so we can stay up-to-date

**Comment by GiacomoCaruso** [comment]
I just opened a PR. It's my first PR ever in my life, so any feedback that can help me to learn and improve is very welcome.

**Comment by rohitpaulk** [comment]
Looks like this was done in #856 (https://github.com/thelounge/lounge/pull/856#issue-198107586)

**Comment by MaxLeiter** [comment]
unless the result gif in #856 is outdated it wasn't fixed

**Comment by rohitpaulk** [comment]
Oh - I thought I saw the headings get hidden in the gif, my bad

**Comment by rohitpaulk** [comment]
Just checked - this is still broken on 2.2.2, but fixed on `master`. 

Screenshots: 

**2.2.2**:

![screen shot 2017-05-29 at 7 11 24 am](https://cloud.githubusercontent.com/assets/3893573/26534092/3ccfb640-443e-11e7-8d01-12cce048ca03.png)

**master (https://github.com/thelounge/lounge/tree/1f1b025)**:

![screen shot 2017-05-29 at 7 11 32 am](https://cloud.githubusercontent.com/assets/3893573/26534094/3d70e65a-443e-11e7-81df-2cc31a5e30fb.png)

Looks like it is [this commit](https://github.com/thelounge/lounge/commit/b1e9a7ffda5bdca68b29c9229d8f954b2d9b0cb0) that did the trick.

**Comment by astorije** [comment]
This should be addressed by v2.3.0.
