### ISSUE TITLE
install thelounge

### ISSUE THREAD

**Issue by Yusif1** [thelounge/lounge#778]
Hi all, i am new with thelounge client, and can't find full information about setting
where should i install thelounge on irc server or on website with change setting in config ?
please i need help , thanks

**Comment by MiniDigger** [comment]
the readme got the informations you need. 
you don't install lounge on a irc server, it is its one thing and connects to irc servers. 
you just need a server that is accessible from the international and has none.js installed.

**Comment by Yusif1** [comment]
thanks MiniDigger, in that case i did it right because i uploaded the lounge to my website and i set config to connect to the irc server but its not connecting , can't find where the problem 
http://icq-chat.com/lounge

**Comment by MiniDigger** [comment]
node.js is the platform lounge is running on. you can't run lounge on a apache/nginx webserver.

**Comment by Yusif1** [comment]
what should i do now, it not connect to irc server although i set config correctly
what i missed ?
http://icq-chat.com/lounge

**Comment by lb1c** [comment]
Just stick to the Install instructions. 
https://github.com/thelounge/lounge#running-stable-releases-from-npm-recommended
You'll need to have node.js and npm installed and working prior to start installing/using TheLounge.

**Comment by astorije** [comment]
Hi @Yusif1, welcome!

It looks like you need to run `npm run build` (which should run along with `npm install`). Actually, it may look like you are trying to server the index.html file without running the Node server, which won't work.

As others have suggested, I recommend you go through recommended documentation [here](https://github.com/thelounge/lounge#installation-and-usage) or [there](https://thelounge.github.io/docs/getting_started/install.html). The latter is more complete but sadly outdated.

For these types of questions, instead of using these issues (intended as bug tracker), I recommend asking them on the IRC channel, `#thelounge` on Freenode. If you are unable to run another IRC client right now, use our [demo](https://avatar.playat.ch:1000/). It does not connect to Freenode but to a relay server. You will not see anyone on the channel, but whatever you post/ask will be relayed to the 150+ users of the channel and their answers relayed back to you.

Hope that helps!
