### ISSUE TITLE
ctrl+arrow left/right Should change the server.

### ISSUE THREAD

**Issue by Zelaf** [thelounge/lounge#807]
ctrl+arrow up/down Already changes the channels but it would be cool if ctrl+arrow left/right changes the server view as well. Would probably help users with tons of connected servers and channels.

**Comment by astorije** [comment]
This is very likely to break OS patterns. For example, on macOS, <kbd>cmd</kbd>+<kbd>left</kbd>/<kbd>right</kbd> is used as Home/End buttons and <kbd>ctrl</kbd>+<kbd>left</kbd>/<kbd>right</kbd> is used to switch across desktops. I'm suspecting Windows/Linux will have the same issues.

Because there is the alternative (not as convenient, I understand) of moving across channels and using mouse/touchscreen, we will close it for now.

Thanks for the idea though!

**Comment by Zelaf** [comment]
Currently on Windows, Nothing happens when pressing ctrl + left/right and on Linux it depends on DE. But I see your point non the less.
