### ISSUE TITLE
Date separator logic for older messages

### ISSUE THREAD

**Issue by MaxLeiter** [thelounge/lounge#859]
If you have older messages not loaded/rendered (i.e. "Show more" button is visible), the date separator is displayed below the `Show more...` button, even if the older messages are the same date as rendered ones.

@PolarizedIons thinks this is a benefit, I disagree - would like to hear others opinions

**Comment by PolarizedIons** [comment]
This was by design choice, since you'd want to know what date the messages at the top of the page was, no matter if the messages 'before' the older messages button was the same date. It is removed automaticly when the show more button is pressed

I'm open to it if you guys have diffrent opinions on it, just explaining why it was done

**Comment by astorije** [comment]
I wouldn't want anything above the `Show older messages` button.

But more importantly, let's get rid of the `Show older messages` button! I would really looove for https://github.com/thelounge/lounge/issues/207 to make it...

**Comment by MaxLeiter** [comment]
We don't want anything above it visibly, the problem is it's not so much a date "separator", its a date reminder that sometimes falls between days

**Comment by astorije** [comment]
@MaxLeiter, then I'm probably not following. Do you have a screenshot or GIF to show the issue?

**Comment by YaManicKill** [comment]
@MaxLeiter Yeah, I understand what you are saying, and I understand the confusion that it is because the date separator should be the first thing in the day showing.

However, I thought I would look at how slack does it (out of interest). And (for the split second that you are at the top, before it loads more messages, like we want to do in #207), it shows the date separator at the top. So...I would say we leave it as is, personally.

**Comment by PolarizedIons** [comment]
@astorije His argument is that the date separator shows the change in dates, yet it is showed bellow the 'Show more messages' button, when those messages are on the same date

Like this: https://gfycat.com/SkeletalFluffyCurlew

**Comment by MaxLeiter** [comment]
seeing as this is how Slack handles it, I think its safe to close.
