### ISSUE TITLE
Have /away toggle state

### ISSUE THREAD

**Issue by MaxLeiter** [thelounge/lounge#870]
`/away` should toggle your state - i.e., if you're away, it should mark you as `/back`, and if you're around, it should mark you as `/away`

**Comment by MaxLeiter** [comment]
Why would anyone ever try to `/away` twice though? I think we should look at how other clients do it - i'll do some research tomorrow

**Comment by astorije** [comment]
> Why would anyone ever try to /away twice though?

Just see my previous comment about cognitive disabilities :)
I still believe this would be bad and confusing UX.

**Comment by xPaw** [comment]
> Why would anyone ever try to /away twice though? 

`/away getting food` then you realize you have to go for who knows how long, then you do `/away`

**Comment by autra** [comment]
> I very much like the current semantic: `/away` marks you as away, `/back` marks you as not away.

Just saying that the away command is part of the Irc specification though (https://tools.ietf.org/html/rfc1459) which *does* state that `/away` without params should toggle.

**Comment by brunnre8** [comment]
@autra read the linked PR... that specific argument was addressed

**Comment by autra** [comment]
`/help away` in thelounge does say: 

> AWAY :[MSG]
>
> Without an argument, it will set you back.  With an argument,
> it will set you as AWAY with the specified message.

To elaborate, my path was the following:

- Use `/away` in a channel, thinking it will clear my status.
- I had no feedback whatsoever (the feedback in on the `Freenode` tab, not where you type the command, but the sidebar doesn't display that i have a new message on `Freenode` tab) so I thought it worked ok
- Later, much later, I realized that it didn't work
- I did `/help away`, which didn't clear the confusion at all
- I searched thelounge issues and find this one
- yes, sorry, I didn't read the linked PR, mainly because of this comment above
> The rationale behind this is explained in #745 (but we did not mention the toggle).


So, the user experience is not great here. Let me suggest several possible improvements:

- change the `/help away` message, mandatory imo. Most users won't care about the standard as soon as things are explained properly. Also populate the `/help back` command (currently says "back Help not found")
- display clearly the current user status somewhere (to make it obvious what your current status is)
- and/or display the `You have been marked as <>` message in all channels (like weechat does for example)
- maybe also have a visual hint in the sidebar when something happens in the server chan?

If thelounge decides to go against the standard (which is understandable in this case, no strong opinion either way), please document it and show it properly in your UI, otherwise you'll need to downvote many more users like me in issues like this one @brunnre8 😆

Thanks for your understanding.

**Comment by brunnre8** [comment]
*Now* you are giving a helpful report and in fact this should go into its own issue as this is indeed not desired.
